---
output:
  bookdown::html_document2:
    fig_caption: yes
editor_options:
  chunk_output_type: inline
---

# Mutational signatures

```{r setup, include=FALSE}
# Global knit options
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

# Global chunk options
knitr::opts_chunk$set(echo=FALSE, tidy=TRUE, warning=FALSE, message=FALSE)
```

```{r, echo=FALSE}
library(ape)
library(circlize)
library(ggplot2)
library(cowplot)
library(ComplexHeatmap)
library(tidyverse)
library(grid)
library(gtable)
library(gtools)
library(RColorBrewer)
library(openxlsx)

set.seed(349861275)
font_size <- 10

source("src/global_vars.R")
source("src/plot_mutational_signatures_heatmap.R")
```

```{r}

# Load data
props_tbl <- read_tsv("/work/shah/funnellt/projects/spectrum-mutsig/analysis/signatures/spectrum_mmctm_props_standardized.tsv")
labels_tbl <- read_tsv("/work/shah/funnellt/projects/spectrum-mutsig/analysis/labels/spectrum-ov-tnbc_labels.tsv")
tree_nwk <- read.tree("/work/shah/funnellt/projects/spectrum-mutsig/analysis/signatures/spectrum_mmctm_props_ward_clusters.newick")
clusters_tbl <- read_tsv("/work/shah/funnellt/projects/spectrum-mutsig/analysis/signatures/spectrum_mmctm_props_ward_clusters.tsv")

```

```{r}

# Mutational signature labels
## Filter SPECTRUM samples
labels_df <- labels_tbl %>% 
  left_join(clusters_tbl, by = "sample_id") %>%
  filter(cohort == "SPECTRUM") %>%
  dplyr::select(-patient_id) %>%
  left_join(bulk_dna_meta_tbl, by = c("sample_id" = "isabl_id")) %>%
  filter(patient_id %in% included_patients) %>%
  filter(qc_status == "Pass") %>%
  filter(consensus_signature != "Undetermined") %>%
  mutate(consensus_signature = ordered(consensus_signature, levels = names(clrs$consensus_signature[names(clrs$consensus_signature)!="NA"]))) %>%
  mutate(consensus_signature = as.factor(consensus_signature)) %>%
  as.data.frame()

labels_df$consensus_signature = factor(labels_df$consensus_signature, levels = names(clrs$consensus_signature))

# Mutational signature proportions
props_df <- props_tbl %>%
  dplyr::select(colnames(props_tbl)[colnames(props_tbl) %in% labels_df$sample_id]) %>%
  as.data.frame()
rownames(props_df) <- props_tbl$topic

## Remap labels to PCAWG COSMIC notation
rownames(props_df) <- plyr::mapvalues(
  rownames(props_df),
  from = c(
    "Age",
    "SBS5",
    "SBS40",
    "POLH",
    "MMRD1",
    "MMRD2",
    "APOBEC1",
    "APOBEC2",
    "HRD"
  ),
  to = c(
    "SBS1 (Age)",
    "SBS5 (Age)",
    "SBS40 (Age)",
    "SBS9 (Pol η)",
    "SBS26 (MMRD1)",
    "SBS44 (MMRD2)",
    "SBS2 (APOBEC1)",
    "SBS13 (APOBEC2)",
    "SBS3 (HRD)"
  )
)
colnames(props_df) <-
  plyr::mapvalues(colnames(props_df),
                  from = labels_df$sample_id,
                  to = labels_df$patient_id_short)

labels_df <- labels_df %>% 
  mutate(sample_id = patient_id_short)

```

```{r, fig.height = 4.55, fig.width = 6.4}

plot_size <- get_plot_size(props_df, TRUE)

ht <- plot_props_heatmap(props_df, as.hclust(tree_nwk), clusters_tbl, labels_df, FALSE)

pdf("figures/310_cancer_cells/310_mutational_signatures.pdf", height = plot_size$height, width = plot_size$width, useDingbats = FALSE)

ht <- draw(ht,
     heatmap_legend_side = "left",
     annotation_legend_side = "left",
     merge_legends = TRUE,
     padding = unit(c(plot_size$bottom_pad, 0.25, 0.25, 0.25), "cm"))

print(ht)

dev.off()

```

```{r}
signatures_list <- list(
  "Mutational signatures" = select(db$mutational_signatures,
                                   c("patient_id","consensus_signature","wgs_signature","impact_signature","myriad_signature")),
  # "Signature counts" = ,
  "Signature proportions" = props_df
)

wb <- createWorkbook()
lapply(seq_along(signatures_list), function(i){
  addWorksheet(wb=wb, sheetName = names(signatures_list[i]))
  writeData(wb, sheet = i, signatures_list[[i]][-length(signatures_list[[i]])])
})

saveWorkbook(wb, "tables/mutational_signatures.xlsx", overwrite = TRUE)
```