---
title: "Cancer cell embeddings"
subtitle: "MSK SPECTRUM"
author:
  - "Florian Uhlitz"
  - "Ignacio Vazquez-Garcia"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document: 
    df_print: kable
    number_sections: yes
    toc: yes
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}

knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = F)

```

# Figure 3 

```{r chunk_320_010}

library(magrittr)
library(tidyverse)
library(Seurat)
library(readxl)
library(cowplot)
# library(colorblindr)
library(viridis)
# library(magick, lib.loc = "/home/uhlitzf/miniconda3/lib/R/library")
library(ggpubr)

```

```{r chunk_320_020}

## load global vars: 
source("src/global_vars.R")

# scrna_meta_tbl
# clrs
# markers_v7
# markers_v7_super
# cell_type_super_lookup

```

```{r chunk_320_040}

## load full seurat objects with expression data
# seu_obj_tc <- read_rds("/work/shah/users/uhlitzf/data/SPECTRUM/freeze/v5/T.cell_processed_filtered_sub.rds")
# seu_obj_cc <- read_rds(paste0("/work/shah/users/uhlitzf/data/SPECTRUM/freeze/v5/Ovarian.cancer.cell_processed_filtered.rds"))
seu_obj_cc <- read_rds("/work/shah/users/uhlitzf/data/SPECTRUM/freeze/v7/Ovarian.cancer.super_processed_filtered_annotated.rds")
marker_tbl <- read_tsv("/work/shah/users/uhlitzf/data/SPECTRUM/freeze/v7/supplementary_tables/Ovarian.cancer.super_marker_table_annotated.tsv")

marker_tbl_top <- marker_tbl %>% 
  filter(avg_logFC > 0.5, 
         p_val_adj < 0.01,
         pct.1 > 0.2,
         pct.2 < 0.8,
         !is.na(cluster_label)) %>% 
  group_by(cluster_label) %>% 
  slice(1:50)

myfeatures <- c("UMAP_1", "UMAP_2", "umapharmony_1", "umapharmony_2", "sample", "doublet", "nCount_RNA", "nFeature_RNA", "percent.mt", "doublet_score", "cell_type")

my_subtypes <- names(clrs$cluster_label$Ovarian.cancer.super)
coi <- "Ovarian.cancer.super"

mois <- c("HRD-Dup", "HRD-Del", "FBI")
gois <- c("HLA-A", "HLA-B", "HLA-C", "B2M", "HLA-DRA", "HLA-DRB1", "CD274")
sois <- c("Adnexa", "Omentum", "Ascites")
pois_short <- c("JAK.STAT", "NFkB", "TNFa", "TGFb", "Hypoxia")
pois <- paste0(pois_short, ".pathway")
all_pws <- grep("pathway", colnames(seu_obj_cc@meta.data), value = T)
all_pws_short <- str_remove_all(all_pws, "\\.pathway")

```

```{r chunk_320_050}

plot_data <- cbind(cell_id = colnames(seu_obj_cc), FetchData(seu_obj_cc, c("umapharmony_1", "umapharmony_2", "umappca_1", "umappca_2", "RNA_snn_res.0.2", "sample", "cluster_label", gois, all_pws))) %>% 
  as_tibble() %>% 
  left_join(scrna_meta_tbl, by = "sample") %>% 
  filter(!is.na(consensus_signature)) %>% 
  mutate(tumor_megasite = str_replace_all(tumor_megasite, "Other", "Non-adnexa")) %>% 
  mutate(cluster_label = ordered(cluster_label, levels = names(clrs$cluster_label$Ovarian.cancer.super)),
         cluster_number = as.numeric(cluster_label)) %>% 
  mutate(umapscaled_1 = scales::rescale(umapharmony_1),
         umapscaled_2 = scales::rescale(umapharmony_2))

base_umap <- ggplot(plot_data) +
  coord_fixed() +
  NoAxes() +
  theme(legend.position = c(0, 1),
        legend.justification = c("left", "top"),
        legend.box.just = "left",
        legend.margin = margin(1, 1, 1, 1),
        legend.text = element_text(size = 14, margin = margin(0, 10, 0, 0)),
        legend.spacing.x = unit(0, "npc"), 
        legend.title = element_blank(),
        plot.title = element_text(hjust = 0.5, vjust = 0.5, face = "plain", size = 22))


```

```{r chunk_320_060}

pt.size <- 0.1
pt.size2 <- 0.2
pt.size.mini <- 0.01
pt.alpha <- 0.05
pt.alpha.mini <- 0.02
dpi <- 150

median_tbl <- plot_data %>%
  group_by(patient_id_short) %>% 
  summarise(umappca_1 = median(umappca_1), 
            umappca_2 = median(umappca_2),
            umapscaled_1 = median(umapscaled_1),
            umapscaled_2 = median(umapscaled_2))

median_tbl_cluster <- plot_data %>%
  group_by(cluster_label, cluster_number) %>% 
  summarise(umapharmony_1 = median(umapharmony_1), 
            umapharmony_2 = median(umapharmony_2),
            umapscaled_1 = median(umapscaled_1),
            umapscaled_2 = median(umapscaled_2))

umap_pca_mutsig <- base_umap + 
  ggrastr::geom_point_rast(aes(umappca_1, umappca_2, color = consensus_signature), 
                           size = pt.size, alpha = pt.alpha, raster.dpi = dpi) +
  # geom_text(aes(umappca_1, umappca_2, label = patient_id_short), data = median_tbl) + 
  geom_label(aes(umappca_1, umappca_2, label = patient_id_short), color = "black",
             data = median_tbl, label.size = unit(0, "mm"), label.r = unit(0, "mm"),
             alpha = 0.5) +
  scale_color_manual(values = clrs$consensus_signature) +
  guides(color = guide_legend(override.aes = list(size = 4, alpha = 1),
                              ncol = 1, 
                              label.position = "right")) +
  labs(title = "Uncorrected")

umap_mutsig <- base_umap + 
  ggrastr::geom_point_rast(aes(umapharmony_1, umapharmony_2, color = consensus_signature), 
                           size = pt.size2, alpha = pt.alpha, raster.dpi = dpi) +
  scale_color_manual(values = clrs$consensus_signature) +
  guides(color = guide_legend(override.aes = list(size = 4, alpha = 1),
                              ncol = 1, 
                              label.position = "right")) +
  guides(color = F) + 
  labs(title = "Corrected (harmony)")

umap_pca_cluster <- base_umap + 
  ggrastr::geom_point_rast(aes(umappca_1, umappca_2, color = cluster_label), 
                           size = pt.size, alpha = pt.alpha, raster.dpi = dpi) +
  geom_text(aes(umappca_1, umappca_2, label = patient_id_short), data = median_tbl) + 
  scale_color_manual(values = clrs$cluster_label$Ovarian.cancer.super) +
  guides(color = guide_legend(override.aes = list(size = 4, alpha = 1),
                              ncol = 1, 
                              label.position = "right")) +
  labs(title = "Cluster")

umap_cluster <- base_umap + 
  ggrastr::geom_point_rast(aes(umapharmony_1, umapharmony_2, color = cluster_label), 
                           size = pt.size2, alpha = pt.alpha, raster.dpi = dpi) +
  scale_color_manual(values = clrs$cluster_label$Ovarian.cancer.super) +
  geom_point(aes(umapharmony_1, umapharmony_2), 
            color = "white", alpha = 0.5, size = 6, 
            data = median_tbl_cluster) +
  geom_text(aes(umapharmony_1, umapharmony_2, label = cluster_number), 
            color = "black",
            data = median_tbl_cluster) +
  guides(color = guide_legend(override.aes = list(size = 4, alpha = 1),
                              ncol = 1, 
                              label.position = "right")) +
  guides(color = F) + 
  labs(title = "Cluster") +
  annotate(geom = "text", 
           x = (max(plot_data$umapharmony_1) + min(plot_data$umapharmony_1))/2,
           y = min(plot_data$umapharmony_2), color = "black",
           label = paste0("n = ", nrow(distinct(plot_data, cell_id))))

cluster_legend <- cowplot::get_legend(umap_pca_cluster)

umap_pca_jak_stat <- base_umap + 
  # geom_point(aes(umappca_1, umappca_2), color = "grey80",
  #            size = pt.size, alpha = pt.alpha, 
  #            data = filter(plot_data, JAK.STAT.pathway <= 0)) +
  ggrastr::geom_point_rast(aes(umappca_1, umappca_2, color = JAK.STAT.pathway), 
                           size = pt.size, alpha = pt.alpha, raster.dpi = dpi, 
             data = mutate(plot_data, JAK.STAT.pathway = ifelse(JAK.STAT.pathway > 4, 4, JAK.STAT.pathway))) +
  geom_text(aes(umappca_1, umappca_2, label = patient_id_short), data = median_tbl) + 
  scale_color_gradientn(colours = viridis(9), breaks = c(0, 2, 4), limits = c(min(plot_data$JAK.STAT.pathway), 4), labels = c(0, 2, "≥4")) +
  labs(title = "JAK-STAT signaling")

umap_jak_stat <- base_umap + 
  # geom_point(aes(umapharmony_1, umapharmony_2), color = "grey80",
  #            size = pt.size, alpha = pt.alpha, 
  #            data = filter(plot_data, JAK.STAT.pathway <= 0)) +
  ggrastr::geom_point_rast(aes(umapharmony_1, umapharmony_2, color = JAK.STAT.pathway), 
             size = pt.size2, alpha = pt.alpha, raster.dpi = dpi,
             data = mutate(plot_data, JAK.STAT.pathway = ifelse(JAK.STAT.pathway > 4, 4, JAK.STAT.pathway))) +
  scale_color_gradientn(colours = viridis(9), breaks = c(0, 2, 4), limits = c(min(plot_data$JAK.STAT.pathway), 4), labels = c(0, 2, "≥4")) +
  labs(title = "JAK-STAT signaling")

umap_genes_data <- plot_data %>% 
  #sample_n(10000) %>% 
  select(umapharmony_1, umapharmony_2, gois) %>% 
  gather(key, value, -umapharmony_1, -umapharmony_2) %>% 
  mutate(value = ifelse(value > 2, 2, value)) %>% 
  filter(key %in% gois) %>% 
  mutate(key = ordered(key, levels = gois)) %>% 
  filter(key == "CD274")

umap_cd274 <- ggplot() + 
  ggrastr::geom_point_rast(aes(umapharmony_1, umapharmony_2), color = "grey80",
                           size = pt.size2, alpha = pt.alpha, 
                           raster.dpi = 15, scale = 0.2,
                           data = filter(umap_genes_data, value == 0)) +
  ggrastr::geom_point_rast(aes(umapharmony_1, umapharmony_2, color = value), 
                           size = 2, alpha = pt.alpha, 
                           raster.dpi = 15, scale = 0.2,
                           data = filter(umap_genes_data, value > 0)) +
  # scale_color_gradientn(colours = viridis(9)) +
  # geom_point(aes(umapharmony_1, umapharmony_2), 
  #            color = "white", alpha = 0.25, size = 6, 
  #            data = median_tbl_cluster) +
  # geom_text(aes(umapharmony_1, umapharmony_2, label = cluster_number), 
  #           color = "black",
  #           data = median_tbl_cluster) +
  scale_color_gradientn(colours = viridis(9), labels = c(0, 1, "≥2"),
                        breaks = c(0, 1, 2), limits = c(0, 2)) +
  remove_xaxis +
  remove_yaxis + 
  theme(aspect.ratio = 1) +
  facet_wrap(~key, nrow = 1) +
  labs(color = "Expr.")

umap_pathways <- plot_data %>% 
  #sample_n(10000) %>% 
  select(umapharmony_1, umapharmony_2, contains("pathway")) %>% 
  gather(key, value, -umapharmony_1, -umapharmony_2) %>% 
  mutate(value = ifelse(value > 4, 4, value),
         value = ifelse(value < -1, -1, value)) %>% 
  filter(key %in% pois) %>% 
  mutate(key = ordered(str_remove_all(key, ".pathway"), 
                       levels = str_remove_all(pois, ".pathway"))) %>% 
  ggplot() + 
  ggrastr::geom_point_rast(aes(umapharmony_1, umapharmony_2, color = value), 
                           size = pt.size2, alpha = pt.alpha, raster.dpi = 10, scale = 0.1) +
  # scale_color_gradientn(colours = viridis(9)) +
  geom_point(aes(umapharmony_1, umapharmony_2), 
             color = "white", alpha = 0.25, size = 6, 
             data = median_tbl_cluster) +
  geom_text(aes(umapharmony_1, umapharmony_2, label = cluster_number), 
            color = "black",
            data = median_tbl_cluster) +
  scale_color_gradientn(colours = viridis(9), labels = c("≤-1", 0, 2, "≥4"),
                        breaks = c(-1, 0, 2, 4), limits = c(-1, 4)) +
  remove_xaxis +
  remove_yaxis + 
  theme(aspect.ratio = 1) +
  facet_wrap(~key, nrow = 1) +
  labs(color = "PROGENy\nscore")

```


## UMAP panels

### pca and harmony grids

```{r chunk_320_070, fig.width=20, fig.height=5}

cancer_grid_pca <- ggdraw() +
  draw_plot(add_umap_coord(umap_pca_mutsig), 
            x = 0, y = 0, width = 0.25, height = 1) +
  draw_plot(add_umap_coord(umap_pca_cluster + guides(color = F)), 
            x = 0.24, y = 0, width = 0.25, height = 1) +
  draw_grob(cluster_legend, x = 0.5, y = -0.15, height = 1) +
  draw_plot(add_umap_coord(umap_pca_jak_stat), 
            x = 0.7, y = 0, width = 0.25, height = 1)

cancer_grid_harmony <- ggdraw() +
  draw_plot(add_umap_coord(umap_mutsig), 
            x = 0, y = 0, width = 0.25, height = 1) +
  draw_plot(add_umap_coord(umap_cluster + guides(color = F)), 
            x = 0.24, y = 0, width = 0.25, height = 1) +
  draw_plot(add_umap_coord(umap_jak_stat), 
            x = 0.7, y = 0, width = 0.25, height = 1)

cancer_grid <- ggdraw() +
  draw_plot(add_umap_coord(umap_pca_mutsig), 
            x = 0, y = 0, width = 0.25, height = 1) +
  draw_plot(add_umap_coord(umap_mutsig + guides(color = F)), 
            x = 0.24, y = 0, width = 0.25, height = 1) +
  draw_plot(add_umap_coord(umap_cluster + guides(color = F)), 
            x = 0.48, y = 0, width = 0.25, height = 1) +
  draw_plot(add_umap_coord(umap_jak_stat), 
            x = 0.73, y = 0, width = 0.25, height = 1)


cancer_grid_pca
cancer_grid_harmony
cancer_grid

# ggsave"figures/320_cancer_cell_plotting_umap/003_umap_grid.png", cancer_grid, width = 20, height = 5)
ggsave("figures/320_cancer_cell_plotting_umap/003_umap_grid_pca.png", cancer_grid_pca, width = 20, height = 5)
ggsave("figures/320_cancer_cell_plotting_umap/003_umap_grid_pca.pdf", cancer_grid_pca, width = 20, height = 5)
ggsave("figures/320_cancer_cell_plotting_umap/003_umap_grid_harmony.png", cancer_grid_harmony, width = 20, height = 5)
ggsave("figures/320_cancer_cell_plotting_umap/003_umap_grid_harmony.pdf", cancer_grid_harmony, width = 20, height = 5)
ggsave("figures/320_cancer_cell_plotting_umap/003_umap_grid.png", cancer_grid, width = 20, height = 5)
ggsave("figures/320_cancer_cell_plotting_umap/003_umap_grid.pdf", cancer_grid, width = 20, height = 5)

```

[figures/320_cancer_cell_plotting_umap/003_umap_grid_pca.png](figures/320_cancer_cell_plotting_umap/003_umap_grid_pca.png)

[figures/320_cancer_cell_plotting_umap/003_umap_grid_pca.pdf](figures/320_cancer_cell_plotting_umap/003_umap_grid_pca.pdf)

[figures/320_cancer_cell_plotting_umap/003_umap_grid_harmony.png](figures/320_cancer_cell_plotting_umap/003_umap_grid_harmony.png)

[figures/320_cancer_cell_plotting_umap/003_umap_grid_harmony.pdf](figures/320_cancer_cell_plotting_umap/003_umap_grid_harmony.pdf)

[figures/320_cancer_cell_plotting_umap/003_umap_grid.png](figures/320_cancer_cell_plotting_umap/003_umap_grid.png)

[figures/320_cancer_cell_plotting_umap/003_umap_grid.pdf](figures/320_cancer_cell_plotting_umap/003_umap_grid.pdf)

[figures/320_cancer_cell_plotting_umap/003_umap_genes.pdf](figures/320_cancer_cell_plotting_umap/003_umap_genes.pdf)

[figures/320_cancer_cell_plotting_umap/003_umap_genes.png](figures/320_cancer_cell_plotting_umap/003_umap_genes.png)

### pathways of interest

```{r chunk_320_072, fig.width=10, fig.height=2.5}

# umap_pathways_grid <- ggdraw() + 
#   draw_plot(add_umap_coord(umap_pathways + remove_guides), x = 0, y = 0, width = 1, height = 1) +
#   draw_grob(get_legend(umap_pathways), x = 0.7, y = -0.25)
# umap_pathways_grid

add_umap_coord(umap_pathways, x_offset = -0.15, textsize = 3)

ggsave("figures/320_cancer_cell_plotting_umap/003_umap_pathways.pdf",
       add_umap_coord(umap_pathways, x_offset = -0.15, textsize = 3), 
       width = 10, height = 2.5)
ggsave("figures/320_cancer_cell_plotting_umap/003_umap_pathways.png", 
       add_umap_coord(umap_pathways, x_offset = -0.15, textsize = 3), 
       width = 10, height = 2.5)

```

[figures/320_cancer_cell_plotting_umap/003_umap_pathways.png](figures/320_cancer_cell_plotting_umap/003_umap_pathways.png)

[figures/320_cancer_cell_plotting_umap/003_umap_pathways.pdf](figures/320_cancer_cell_plotting_umap/003_umap_pathways.pdf)

## Kernel density UMAPs

```{r chunk_320_073, fig.width=7, fig.height=5}

source("src/umap_kernel.R")

rdbu <- rev(RColorBrewer::brewer.pal(7, "RdBu"))

kernel_umap_wrapper <- function(
  kernel_subsets_a = c("FBI"),
  kernel_subsets_b = c("HRD-Dup", "HRD-Del", "TD"),
  quench = 0.015,
  kernel_group_var = consensus_signature,
  n = 200,
  h = 0.2,
  kernel_size = 0.01,
  plot_title = paste0(kernel_subsets_a, "\nvs ", 
                      kernel_subsets_b)
) {
  
  kernel_group_var <- enquo(kernel_group_var)
  
  data_tbl <- plot_data
  
  if(as_label(kernel_group_var) == "consensus_signature") {
    data_tbl <- plot_data %>% filter(tumor_supersite != "Ascites")
  }
  
  if(as_label(kernel_group_var) == "patient_id_short") {
    data_tbl <- plot_data %>% filter(tumor_supersite != "Ascites")
  }
  
  kernel_tbl <- kde2d_contrast(
    data_tbl = data_tbl,
    x = umapharmony_1, y = umapharmony_2, kernel_group = !!kernel_group_var,
    kernel_subsets_a = kernel_subsets_a, kernel_subsets_b = kernel_subsets_b,
    quench = quench, n = n, h = h
  ) %>%
    filter(value.x > 0.001 & value.y > 0.001)
  
  kernel_umap <- ggplot() +
    ggrastr::geom_point_rast(aes(umapscaled_1, umapscaled_2), 
                             color = "grey80", size = 0.01, alpha = 0.02, 
                             data = plot_data,
                             raster.dpi = 10, scale = 0.1) +
    ggrastr::geom_point_rast(aes(x, y, color = value_scaled), 
                             data = kernel_tbl, size = kernel_size, 
                             raster.dpi = 10, scale = 0.1) +
    # geom_point(aes(umapscaled_1, umapscaled_2), color = "white",
    #            data = median_tbl_cluster, alpha = 0.1, size = 6) +
    geom_text(aes(umapscaled_1, umapscaled_2, label = cluster_number), 
              color = "black",
              data = median_tbl_cluster) +
    scale_color_gradientn(colours = rdbu,
                          values = scales::rescale(c(min(kernel_tbl$value_scaled), 0,
                                                     max(kernel_tbl$value_scaled)))) +
    guides(color = guide_colorbar(label.position = "right",
                                  title.position = "top",
                                  title.hjust = 0,
                                  title.vjust = 1,
                                  direction = "vertical")) +
    theme(aspect.ratio = 1,
          legend.key.height = unit(0.08, "npc"),
          legend.key.width = unit(0.025, "npc"),
          legend.position = c(-0.1, 0.95),
          legend.justification = c("left", "top"),
          plot.title = element_text(hjust = 0.5, vjust = 0.5, face = "plain", size = 18)) + 
    labs(color = paste0("Enrichm."),
         title = plot_title) +
    remove_xaxis +
    remove_yaxis
  
  return(kernel_umap)
}

k1 <- kernel_umap_wrapper("HRD-Dup", c("HRD-Del"), 0.015)
k2 <- kernel_umap_wrapper("HRD-Dup", c("FBI"), 0.015) + remove_guides
k3 <- kernel_umap_wrapper("HRD-Del", c("FBI"), 0.015) + remove_guides
# k4 <- kernel_umap_wrapper("TD", c("FBI", "HRD-Dup", "HRD-Del"), 0.015) + remove_guides
ks1 <- kernel_umap_wrapper("Non-adnexa", c("Adnexa"), 0.015, tumor_megasite)
ks2 <- kernel_umap_wrapper("Ascites", c("Adnexa"), 0.030, tumor_megasite) + remove_guides
ks3 <- kernel_umap_wrapper("Ascites", c("Non-adnexa"), 0.030, tumor_megasite) + remove_guides

kernel_grid <- ggdraw() +
  draw_plot(plot_grid(k1 + remove_guides, 
                      k2, k3,
                      ks1 + remove_guides, 
                      ks2, ks3,
                      nrow = 2, align = "hv"), 
            width = 0.88, height = 1, x = -0.02) +
  draw_grob(get_legend(k1), x = 0.97, y = -0.25)

kernel_grid

ggsave("figures/320_cancer_cell_plotting_umap/320_umap_cancer_kernels.pdf", width = 7, height = 5)
ggsave("figures/320_cancer_cell_plotting_umap/320_umap_cancer_kernels.png", width = 7, height = 5)

```

```{r chunk_320_074}

patient_ids <- plot_data %>%
  filter(tumor_supersite != "Ascites") %>% 
  filter(consensus_signature %in% mois) %>% 
  group_by(consensus_signature) %>% 
  summarise(patient_id_short = unique(patient_id_short)) %>%
  arrange(consensus_signature, patient_id_short) %>%
  ungroup() %>%
  select(patient_id_short, consensus_signature) %>%
  deframe()

kernel_umap_wrapper("003", names(patient_ids[patient_ids != "HRD-Dup"]), quench = 0.03, kernel_group_var = patient_id_short, n = 50, h = 0.5, kernel_size = 5) + remove_guides

kernel_list <- list()

kernel_patient_wrapper <- function(csoi) {
  lapply(names(patient_ids[patient_ids == csoi]),
       function(x) kernel_umap_wrapper(x, names(patient_ids[patient_ids != csoi]), 0.015, patient_id_short, n = 50, h = 0.5, kernel_size = 5, plot_title = x))
}

kernel_list$`HRD-Dup` <- lapply(kernel_patient_wrapper("HRD-Dup"), add, remove_guides)
kernel_list$`HRD-Del` <- lapply(kernel_patient_wrapper("HRD-Del"), add, remove_guides)
kernel_list$`FBI` <- lapply(kernel_patient_wrapper("FBI"), add, remove_guides)

kernel_patient_grid <- plot_grid(plotlist = unlist(kernel_list, recursive = F))

ggsave("figures/320_cancer_cell_plotting_umap/kernel_patient_grid.pdf", kernel_patient_grid, width = 12, height = 12)

```

## Cluster marker heatmap

```{r chunk_320_075}

plot_data_markers <- as_tibble(FetchData(seu_obj_cc, c("cluster_label", myfeatures, unique(marker_tbl_top$gene)))) %>% 
  gather(gene, value, -c(1:(length(myfeatures)+1))) %>% 
  left_join(scrna_meta_tbl, by = "sample") %>% 
  mutate(cluster_label = ordered(cluster_label, levels = names(clrs$cluster_label$Ovarian.cancer.super))) %>% 
  group_by(cluster_label, gene) %>% 
  summarise(value = mean(value, na.rm = T)) %>% 
  group_by(gene) %>% 
  mutate(value = scales::rescale(value)) %>% 
  left_join(select(marker_tbl_top, cluster_label_x = cluster_label, gene), by = "gene") %>% 
  ## reverse names vector to flip row-order in heatmap
  mutate(cluster_label_x = ordered(cluster_label_x, levels = names(clrs$cluster_label$Ovarian.cancer.super))) %>% 
  na.omit()

```

```{r chunk_320_080, fig.width=3.75, fig.height=5}

library(ComplexHeatmap)

highlight_genes <- marker_tbl_top %>% 
  group_by(cluster_label) %>% 
  slice(1:2) %>% 
  ## reverse levels also here for row-order flip
  mutate(cluster_label_x = ordered(cluster_label, levels = names(clrs$cluster_label[[coi]]))) %>% 
  ungroup() %>% 
  select(cluster_label_x, gene) %>% 
  na.omit %>% 
  mutate(highlight = T)

plot_data_markers_mat <- plot_data_markers %>% 
  spread(cluster_label, value) %>% 
  left_join(highlight_genes, by = c("gene", "cluster_label_x")) %>% 
  ungroup %>% 
  arrange(desc(cluster_label_x), gene) %>% 
  select(cluster_label_x, gene, highlight, everything())

ha_row <- rowAnnotation(
  `Cell type` = plot_data_markers_mat$cluster_label_x,
  col = list(`Cell type` = clrs$cluster_label[[coi]]),
  show_legend = F,
  annotation_name_side = "top"
)

ha_col <- columnAnnotation(
  `Cell type` = anno_block(gp = gpar(fill = clrs$cluster_label[[coi]], col = NA),
                           labels = as.character(1:10)), 
  show_legend = F,
  annotation_name_side = "left",
  annotation_name_rot = 0
)

gene_idx <- plot_data_markers_mat$highlight == TRUE

ha_genes <- rowAnnotation(
  link = anno_mark(
    at = which(gene_idx),
    labels = plot_data_markers_mat$gene[which(gene_idx)],
    labels_gp = gpar(fontsize = 10), padding = unit(1, "mm"),
    side = "left",
    labels_rot = 0
  )
)

marker_heatmap <- Heatmap(
  as.matrix(plot_data_markers_mat[,-c(1:3)]), 
  heatmap_legend_param = list(
    title = "Scaled expression", 
    title_position = "leftcenter-rot"
  ),
  row_order = 1:length(plot_data_markers_mat$cluster_label_x),
  row_split = plot_data_markers_mat$cluster_label_x, 
  column_split = 1:length(colnames(plot_data_markers_mat)[-c(1:3)]),
  column_order = colnames(plot_data_markers_mat)[-c(1:3)], 
  column_names_side = "top",
  right_annotation = ha_row,
  left_annotation = ha_genes,
  top_annotation = ha_col,
  cluster_rows = F, 
  row_title = NULL,
  column_title = NULL,
  col = viridis(9)
)

# marker_heatmap
heatmap_grob <- grid.grabExpr(draw(marker_heatmap), width = 3.75, height = 5)
heat_grid <- ggdraw() + 
  draw_grob(heatmap_grob)

heat_grid

ggsave("figures/320_cancer_cell_plotting_umap/003_cluster_marker_heatmap.png", heat_grid, width = 3.75, height = 5)
ggsave("figures/320_cancer_cell_plotting_umap/003_cluster_marker_heatmap.pdf", heat_grid, width = 3.75, height = 5)

```

[figures/320_cancer_cell_plotting_umap/003_cluster_marker_heatmap.png](figures/320_cancer_cell_plotting_umap/003_cluster_marker_heatmap.png)

[figures/320_cancer_cell_plotting_umap/003_cluster_marker_heatmap.pdf](figures/320_cancer_cell_plotting_umap/003_cluster_marker_heatmap.pdf)


## Violins 

```{r chunk_320_081, fig.width=22, fig.height=3.5}

plot_data_vio <- plot_data %>% 
  # sample_n(10000) %>% 
  select(umapharmony_1, umapharmony_2, cluster_label, consensus_signature, consensus_signature_short, tumor_supersite, tumor_megasite, all_of(gois), all_of(pois), sample_id, patient_id_short) %>% 
  gather(key, value, -umapharmony_1, -umapharmony_2, -cluster_label, -consensus_signature, -consensus_signature_short, -tumor_supersite, -tumor_megasite, -sample_id, -patient_id_short) %>% 
  # mutate(value = ifelse(value > 3, 3, value)) %>% 
  filter(str_detect(cluster_label, "^Cancer.cell")) %>% 
  mutate(cluster_label_num = str_remove_all(cluster_label, "Cancer.cell.")) %>% 
  mutate(tumor_megasite = str_replace_all(tumor_megasite, "Other", "Non-adnexa")) %>% 
  mutate(tumor_megasite = ordered(tumor_megasite, levels = names(clrs$tumor_megasite))) %>% 
  mutate(key = str_remove_all(key, ".pathway")) %>% 
  mutate(key = ordered(key, levels = c(gois, pois_short)))

plot_data_vio_summary <- plot_data_vio %>% 
  group_by(sample_id, key) %>% 
  mutate(value = mean(value, na.rm = T)) %>% 
  distinct(sample_id, key, .keep_all = T) %>% 
  ungroup()

my_comparisons <- list(
  c("HRD-Dup", "HRD-Del"), 
  c("HRD-Dup", "FBI"), 
  c("HRD-Del", "FBI")
)

my_comparisons2 <- list(
  c("HRD", "HRP")
)

# violin_wrapper(cluster_label, "Cluster", pois_short, ".all.", "Expression", c(-1,8), 10, mut_filter = levels(unique(scrna_meta_tbl$consensus_signature)), site_filter = names(clrs$tumor_supersite), facet_site = F)
  
violin_wrapper <- function(group_column, group_var_label, keys, comps, y_label, ylims, ncol, plabel = "p.signif", mut_filter = mois, site_filter = names(clrs$tumor_supersite), facet_site = T) {
  
  group_column <- enquo(group_column)
  yrange <- ylims[2]-ylims[1]
  ylabels <- yrange*c(0.85,0.75,0.65)+ylims[1]
  clrs$cluster_label <- clrs$cluster_label$Ovarian.cancer.super
  
  p <- plot_data_vio %>% 
    filter(key %in% keys) %>% 
    filter(consensus_signature %in% mut_filter) %>% 
    filter(tumor_supersite %in% site_filter) %>% 
    ggplot(aes(!!group_column, value)) +
    geom_violin(aes(!!group_column, value, fill = !!group_column), color = "white", adjust = 2, alpha = 0.5, width = 1.5) +
    geom_boxplot(aes(!!group_column, value, color = !!group_column),
                 width = 0.5, size = 0.75, outlier.shape = NA) +
    geom_boxplot(aes(!!group_column, value, fill = !!group_column),
                 color = "white", width = 0.5, outlier.shape = NA, size = 0.5) +
    scale_color_manual(values = clrs[[as_label(group_column)]]) +
    scale_fill_manual(values = clrs[[as_label(group_column)]]) +
    theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
          axis.title.x = element_blank()) + 
    coord_cartesian(clip = "on", ylim = ylims) +
    labs(y = y_label, color = group_var_label, 
         fill = group_var_label) +
    remove_guides

  if (facet_site) {
    p <- p + facet_grid(tumor_megasite~key)
  } else {
    p <- p + facet_grid(~key)
  }
  
  if (any(unlist(comps) != ".all.")) {
    p <- p + 
      stat_compare_means(comparisons = comps, 
                         data = filter(plot_data_vio_summary, 
                                       key %in% keys, 
                                       consensus_signature %in% mut_filter),
                         label = plabel, label.y = ylabels, 
                         tip.length = 0.01,
                         hide.ns = F)
  }
  
  if (all(unlist(comps) == ".all.")) {
    p <- p + 
      stat_compare_means(ref.group = ".all.", 
                         method.args = list(alternative = "greater"),
                         data = filter(plot_data_vio_summary,
                                       key %in% keys,
                                       consensus_signature %in% mut_filter), 
                         label.y = ylabels[1], hide.ns = T,
                         label = plabel)
  }
  
  return(p)
  
}

```

```{r chunk_320_082, fig.width=22, fig.height=3.5}

boxplot_wrapper <- function(group_column, group_var_label, keys, comps, y_label, ylims, ncol, plabel = "p.signif", mut_filter = mois, site_filter = names(clrs$tumor_supersite), facet_site = T) {
  
  group_column <- enquo(group_column)
  yrange <- ylims[2]-ylims[1]
  ylabels <- yrange*c(0.85,0.75,0.65)+ylims[1]
  clrs$cluster_label <- clrs$cluster_label$Ovarian.cancer.super
  
  boxplot_data <- filter(plot_data_vio_summary, 
                         key %in% keys, 
                         consensus_signature %in% mut_filter,
                         tumor_supersite %in% site_filter,
                         tumor_megasite %in% c("Adnexa", "Non-adnexa"))
  
  boxplot_data_summary <- boxplot_data %>% 
    group_by(!!group_column, tumor_megasite, key) %>% 
    tally
  
  p <- ggplot(boxplot_data, aes(!!group_column, value)) +
    geom_boxplot(aes(!!group_column, value, color = !!group_column),
                 width = 0.5, size = 0.75, outlier.shape = NA) +
    geom_boxplot(aes(!!group_column, value, fill = !!group_column),
                 color = "white", width = 0.5, outlier.shape = NA, size = 0.5) +
    geom_jitter(aes(!!group_column, value),
                color = "black", width = 0.15, size = 0.25, alpha = 0.5) +
    geom_text(aes(x = !!group_column, color = !!group_column, label = n), 
              y = min(boxplot_data$value)-0.1*(max(boxplot_data$value)-min(boxplot_data$value)), 
              data = boxplot_data_summary) +
    scale_color_manual(values = clrs[[as_label(group_column)]]) +
    scale_fill_manual(values = clrs[[as_label(group_column)]]) +
    theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
          axis.title.x = element_blank()) + 
    coord_cartesian(clip = "on", ylim = ylims) +
    labs(y = y_label, color = group_var_label, 
         fill = group_var_label) +
    remove_guides

  if (facet_site) {
    p <- p + facet_grid(tumor_megasite~key)
  } else {
    p <- p + facet_grid(~key)
  }
  
  if (any(unlist(comps) != ".all.")) {
    p <- p + 
      stat_compare_means(comparisons = comps, 
                         data = boxplot_data,
                         label = plabel, label.y = ylabels, 
                         tip.length = 0,
                         hide.ns = F)
  }
  
  if (all(unlist(comps) == ".all.")) {
    p <- p + 
      stat_compare_means(ref.group = ".all.", 
                         method.args = list(alternative = "greater"),
                         data = boxplot_data, 
                         label.y = ylabels[1], hide.ns = T,
                         label = plabel)
  }
  
  return(p)
  
}

# boxplot_wrapper(consensus_signature, "Mutational\nsignature", pois_short, my_comparisons, "PROGENy score", c(-1,3), 10)

```

```{r chunk_320_083, fig.width=5, fig.height=5}

violins_pw_mutsig_site <- violin_wrapper(consensus_signature, "Mutational\nsignature", pois_short, my_comparisons, "PROGENy score", c(-1,5), 10)

violins_pw_mutsig_site
ggsave("figures/320_cancer_cell_plotting_umap/003_pw_violins_site.pdf", 
       violins_pw_mutsig_site, width = 5, height = 5)
ggsave("figures/320_cancer_cell_plotting_umap/003_pw_violins_site.png", 
       violins_pw_mutsig_site, width = 5, height = 5)

violins_pw_mutsig_pval_site <- violin_wrapper(consensus_signature, "Mutational\nsignature", pois_short, my_comparisons, "PROGENy score", c(-1,5), 10, "p.format")

violins_pw_mutsig_pval_site
ggsave("figures/320_cancer_cell_plotting_umap/003_pw_violins_pval_site.pdf", 
       violins_pw_mutsig_pval_site, width = 5, height = 5)
ggsave("figures/320_cancer_cell_plotting_umap/003_pw_violins_pval_site.png", 
       violins_pw_mutsig_pval_site, width = 5, height = 5)


```

```{r chunk_320_084, fig.width=5, fig.height=5}

boxplot_pw_mutsig_site <- boxplot_wrapper(consensus_signature, "Mutational\nsignature", pois_short, my_comparisons, "PROGENy score", c(-1.25,3), 10)

boxplot_pw_mutsig_site
ggsave("figures/320_cancer_cell_plotting_umap/003_pw_boxplot_site.pdf", 
       boxplot_pw_mutsig_site, width = 5, height = 5)
ggsave("figures/320_cancer_cell_plotting_umap/003_pw_boxplot_site.png", 
       boxplot_pw_mutsig_site, width = 5, height = 5)

boxplot_pw_mutsig_pval_site <- boxplot_wrapper(consensus_signature, "Mutational\nsignature", pois_short, my_comparisons, "PROGENy score", c(-1.25,3), 10, "p.format")

boxplot_pw_mutsig_pval_site
ggsave("figures/320_cancer_cell_plotting_umap/003_pw_boxplot_pval_site.pdf", 
       boxplot_pw_mutsig_pval_site, width = 5, height = 5)
ggsave("figures/320_cancer_cell_plotting_umap/003_pw_boxplot_pval_site.png", 
       boxplot_pw_mutsig_pval_site, width = 5, height = 5)


```

```{r chunk_320_085, fig.width=5, fig.height=3}

violins_pw_mutsig <- violin_wrapper(consensus_signature, "Mutational\nsignature", pois_short, my_comparisons, "PROGENy score", c(-1,5), 10, site_filter = names(clrs$tumor_supersite), facet_site = F)

violins_pw_mutsig
ggsave("figures/320_cancer_cell_plotting_umap/003_pw_violins.pdf", 
       violins_pw_mutsig, width = 5, height = 3)
ggsave("figures/320_cancer_cell_plotting_umap/003_pw_violins.png", 
       violins_pw_mutsig, width = 5, height = 3)

violins_pw_mutsig_pval <- violin_wrapper(consensus_signature, "Mutational\nsignature", pois_short, my_comparisons, "PROGENy score", c(-1,5), 10, "p.format", site_filter = names(clrs$tumor_supersite), facet_site = F)

violins_pw_mutsig_pval
ggsave("figures/320_cancer_cell_plotting_umap/003_pw_violins_pval.pdf", 
           violins_pw_mutsig_pval, width = 5, height = 3)
ggsave("figures/320_cancer_cell_plotting_umap/003_pw_violins_pval.png", 
           violins_pw_mutsig_pval, width = 5, height = 3)

```

```{r chunk_320_086, fig.width=5, fig.height=3}

violins_pw_mutsig_short <- violin_wrapper(consensus_signature_short, "Mutational\nsignature", pois_short, my_comparisons2, "PROGENy score", c(-1,5), 10, mut_filter = levels(unique(scrna_meta_tbl$consensus_signature)), site_filter = names(clrs$tumor_supersite), facet_site = F)

violins_pw_mutsig_short
ggsave("figures/320_cancer_cell_plotting_umap/003_pw_violins_short.pdf", 
       violins_pw_mutsig_short, width = 5, height = 3)
ggsave("figures/320_cancer_cell_plotting_umap/003_pw_violins_short.png", 
       violins_pw_mutsig_short, width = 5, height = 3)

violins_pw_mutsig_short_pval <- violin_wrapper(consensus_signature_short, "Mutational\nsignature", pois_short, my_comparisons2, "PROGENy score", c(-1,5), 10, "p.format", mut_filter = levels(unique(scrna_meta_tbl$consensus_signature)), site_filter = names(clrs$tumor_supersite), facet_site = F)

violins_pw_mutsig_short_pval
ggsave("figures/320_cancer_cell_plotting_umap/003_pw_violins_short_pval.pdf", 
       violins_pw_mutsig_short_pval, width = 5, height = 3)
ggsave("figures/320_cancer_cell_plotting_umap/003_pw_violins_short_pval.png", 
       violins_pw_mutsig_short_pval, width = 5, height = 3)

```

```{r chunk_320_087, fig.width=8, fig.height=3}

violins_pw_cluster <- violin_wrapper(cluster_label, "Cluster", pois_short, ".all.", "Expression", c(-1,8), 10, mut_filter = levels(unique(scrna_meta_tbl$consensus_signature)), site_filter = names(clrs$tumor_supersite), facet_site = F)

violins_pw_cluster
ggsave("figures/320_cancer_cell_plotting_umap/003_pw_violins_cluster.pdf", 
       violins_pw_cluster, width = 8, height = 3)
ggsave("figures/320_cancer_cell_plotting_umap/003_pw_violins_cluster.png", 
       violins_pw_cluster, width = 8, height = 3)

violins_pw_cluster_pval <- violin_wrapper(cluster_label, "Cluster", pois_short, ".all.", "Expression", c(-1,8), 10, "p.format", mut_filter = levels(unique(scrna_meta_tbl$consensus_signature)), site_filter = names(clrs$tumor_supersite), facet_site = F)

violins_pw_cluster_pval
ggsave("figures/320_cancer_cell_plotting_umap/003_pw_violins_cluster_pval.pdf", 
       violins_pw_cluster_pval, width = 8, height = 3)
ggsave("figures/320_cancer_cell_plotting_umap/003_pw_violins_cluster_pval.png", 
       violins_pw_cluster_pval, width = 8, height = 3)

```


```{r chunk_320_088, fig.width=6.5, fig.height=5}

violins_hla_mutsig_site <- violin_wrapper(consensus_signature, "Mutational\nsignature", gois[-7], my_comparisons, "Expression", c(0,6.1), 10)

violins_hla_mutsig_site

ggsave("figures/320_cancer_cell_plotting_umap/003_hla_violins_site.pdf", width = 6.5, height = 5)
ggsave("figures/320_cancer_cell_plotting_umap/003_hla_violins_site.png", width = 6.5, height = 5)

violins_hla_mutsig_pval_site <- violin_wrapper(consensus_signature, "Mutational\nsignature", gois[-7], my_comparisons, "Expression", c(0,6.1), 10, "p.format")

violins_hla_mutsig_pval_site

ggsave("figures/320_cancer_cell_plotting_umap/003_hla_violins_pval_site.pdf", width = 6.5, height = 5)
ggsave("figures/320_cancer_cell_plotting_umap/003_hla_violins_pval_site.png", width = 6.5, height = 5)

```


```{r chunk_320_089, fig.width=6, fig.height=5}

boxplot_hla_mutsig_site <- boxplot_wrapper(consensus_signature, "Mutational\nsignature", gois[-7], my_comparisons, "Expression", c(-0.5,4.5), 10)

boxplot_hla_mutsig_site

ggsave("figures/320_cancer_cell_plotting_umap/003_hla_boxplot_site.pdf", width = 6, height = 5)
ggsave("figures/320_cancer_cell_plotting_umap/003_hla_boxplot_site.png", width = 6, height = 5)

boxplot_hla_mutsig_pval_site <- boxplot_wrapper(consensus_signature, "Mutational\nsignature", gois[-7], my_comparisons, "Expression", c(-0.5,4.5), 10, "p.format")

boxplot_hla_mutsig_pval_site

ggsave("figures/320_cancer_cell_plotting_umap/003_hla_boxplot_pval_site.pdf", width = 6, height = 5)
ggsave("figures/320_cancer_cell_plotting_umap/003_hla_boxplot_pval_site.png", width = 6, height = 5)

```

```{r chunk_320_090, fig.width=6.5, fig.height=3.5}

violins_hla_mutsig <- violin_wrapper(consensus_signature, "Mutational\nsignature", gois[-7], my_comparisons, "Expression", c(0,6.1), 10, site_filter = names(clrs$tumor_supersite), facet_site = F)

violins_hla_mutsig

ggsave("figures/320_cancer_cell_plotting_umap/003_hla_violins.pdf", width = 6.5, height = 3.5)
ggsave("figures/320_cancer_cell_plotting_umap/003_hla_violins.png", width = 6.5, height = 3.5)

violins_hla_mutsig_pval <- violin_wrapper(consensus_signature, "Mutational\nsignature", gois[-7], my_comparisons, "Expression", c(0,6.1), 10, "p.format", site_filter = names(clrs$tumor_supersite), facet_site = F)

violins_hla_mutsig_pval

ggsave("figures/320_cancer_cell_plotting_umap/003_hla_violins_pval.pdf", width = 6.5, height = 3.5)
ggsave("figures/320_cancer_cell_plotting_umap/003_hla_violins_pval.png", width = 6.5, height = 3.5)

```

```{r chunk_320_091, fig.width=6.5, fig.height=3.5}

violins_hla_mutsig_short <- violin_wrapper(consensus_signature_short, "Mutational\nsignature", gois[-7], my_comparisons2, "Expression", c(0,6.1), 10, mut_filter = levels(unique(scrna_meta_tbl$consensus_signature)), site_filter = names(clrs$tumor_supersite), facet_site = F)

violins_hla_mutsig_short

ggsave("figures/320_cancer_cell_plotting_umap/003_hla_violins_mutsig_short.pdf", width = 6.5, height = 3.5)
ggsave("figures/320_cancer_cell_plotting_umap/003_hla_violins_mutsig_short.png", width = 6.5, height = 3.5)

violins_hla_mutsig_short_pval <- violin_wrapper(consensus_signature_short, "Mutational\nsignature", gois[-7], my_comparisons2, "Expression", c(0,6.1), 10, "p.format", mut_filter = levels(unique(scrna_meta_tbl$consensus_signature)), site_filter = names(clrs$tumor_supersite), facet_site = F)

violins_hla_mutsig_short_pval

ggsave("figures/320_cancer_cell_plotting_umap/003_hla_violins_mutsig_short_pval.pdf", width = 6.5, height = 3.5)
ggsave("figures/320_cancer_cell_plotting_umap/003_hla_violins_mutsig_short_pval.png", width = 6.5, height = 3.5)

```

```{r chunk_320_092, fig.width=10, fig.height=3.5}

violins_hla_cluster <- violin_wrapper(cluster_label, "Cluster", gois[-7], ".all.", "Expression", c(0,6.1), 10, mut_filter = levels(unique(scrna_meta_tbl$consensus_signature)), site_filter = names(clrs$tumor_supersite), facet_site = F)

violins_hla_cluster

ggsave("figures/320_cancer_cell_plotting_umap/003_hla_violins_cluster.pdf", width = 10, height = 3.5)
ggsave("figures/320_cancer_cell_plotting_umap/003_hla_violins_cluster.png", width = 10, height = 3.5)

violins_hla_cluster_pval <- violin_wrapper(cluster_label, "Cluster", gois[-7], ".all.", "Expression", c(0,6.1), 10, "p.format", mut_filter = levels(unique(scrna_meta_tbl$consensus_signature)), site_filter = names(clrs$tumor_supersite), facet_site = F)

violins_hla_cluster_pval

ggsave("figures/320_cancer_cell_plotting_umap/003_hla_violins_cluster_pval.pdf", width = 10, height = 3.5)
ggsave("figures/320_cancer_cell_plotting_umap/003_hla_violins_cluster_pval.png", width = 10, height = 3.5)



```

## Violin grid main text

```{r chunk_320_100, fig.width=10, fig.height=3}

plot_grid(violins_pw_mutsig, ggdraw(), violins_hla_mutsig, 
          nrow = 1, align = "v", rel_widths = c(0.4, 0.05, 0.45))

ggsave("figures/320_cancer_cell_plotting_umap/003_hla_pw_violins_mutsig.pdf", width = 10, height = 3)

```

## Boxplots pairwise site comparisons

```{r chunk_320_115, fig.width=10, fig.height=3}


plot_data_box_pairwise <- plot_data_vio_summary %>% 
  group_by(patient_id_short, consensus_signature, 
           tumor_megasite, key) %>% 
  summarise(value = mean(value, na.rm = T)) %>% 
  filter(tumor_megasite %in% c("Non-adnexa", "Adnexa")) %>% 
  filter(consensus_signature != "Undetermined") %>% 
  filter(key %in% "TGFb") %>% 
  group_by(patient_id_short, key) %>% 
  filter(n() == 2) %>% 
  ungroup()

ggplot(plot_data_box_pairwise, aes(tumor_megasite, value)) +
  geom_boxplot(aes(tumor_megasite, value, color = tumor_megasite),
               width = 0.5, size = 0.75, outlier.shape = NA) +
  geom_boxplot(aes(tumor_megasite, value, fill = tumor_megasite),
               color = "white", 
               width = 0.5, outlier.shape = NA, size = 0.5) + 
  geom_jitter(aes(tumor_megasite, value),
              color = "black", width = 0.15, size = 0.25, alpha = 0.5) +
  geom_line(aes(tumor_megasite, value, group = patient_id_short), 
            alpha = 0.5) +
  facet_grid(~consensus_signature) +
  stat_compare_means(aes(tumor_megasite, value),
                     comparisons = list(c("Adnexa", "Non-adnexa")), 
                     data = plot_data_box_pairwise, 
                     paired = T,
                     tip.length = 0, hide.ns = F, 
                     label = "p.signif") +
  scale_color_manual(values = clrs$tumor_megasite) +
  scale_fill_manual(values = clrs$tumor_megasite) +
  guides(color = "none", fill = "none") +
  labs(x = "Site", y = "TGFb PROGENy score") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))


```

[figures/320_cancer_cell_plotting_umap/003_hla_violins.pdf](figures/320_cancer_cell_plotting_umap/003_hla_violins.pdf)

[figures/320_cancer_cell_plotting_umap/003_hla_violins.png](figures/320_cancer_cell_plotting_umap/003_hla_violins.png)

## Differential pathway expression in cancer cells

```{r chunk_320_140}

set.seed(42)
sampled_cell_ids <- sample(colnames(seu_obj_cc), 10000)
seu_obj_cc_sub <- subset(seu_obj_cc, cells = sampled_cell_ids)

plot_data_pw <- FetchData(seu_obj_cc, c("umapharmony_1", "umapharmony_2", "sample", "cluster_label", gois, grep("pathway|module", colnames(seu_obj_cc@meta.data), value = T))) %>%
  as_tibble() %>%
  gather(pathway, score, -c(1:4)) %>% 
  left_join(scrna_meta_tbl, by = "sample") %>%
  filter(sort_short == "CD45-", therapy == "pre-Rx") %>% 
  mutate(pathway = str_remove_all(pathway, "\\.pathway")) %>% 
  # filter(str_detect(cluster_label, "Cancer|cancer")) %>% 
  mutate(cluster_label = str_remove_all(cluster_label, "\\.cell")) %>% 
  mutate(tumor_megasite = str_replace_all(tumor_megasite, "Other", "Non-adnexa")) %>% 
  mutate(tumor_megasite = ordered(tumor_megasite, levels = names(clrs$tumor_megasite)))

cut_value <- 2
pathway_summary_wrapper <- . %>% 
  summarise(mean_score = mean(score),
            median_score = median(score)) %>% 
  mutate(median_cut = ifelse(median_score > cut_value, cut_value, 
                             ifelse(median_score < -cut_value, -cut_value, 
                                    median_score))) %>% 
  mutate(mean_cut = ifelse(mean_score > cut_value, cut_value, 
                           ifelse(mean_score < -cut_value, -cut_value, 
                                  mean_score)))


# plot_data_summary_patient <- plot_data_pw %>% 
#   group_by(patient_id_short, consensus_signature, cluster_label, 
#            pathway, tumor_supersite) %>% 
#   pathway_summary_wrapper
# 
# plot_data_summary_mutsig <- plot_data_pw %>% 
#   group_by(consensus_signature, pathway) %>% 
#   pathway_summary_wrapper
# 
# plot_data_summary_mutsig_cluster <- plot_data_pw %>% 
#   group_by(consensus_signature, cluster_label, pathway) %>% 
#   pathway_summary_wrapper

plot_data_summary_cluster <- plot_data_pw %>%
  group_by(cluster_label, pathway) %>%
  pathway_summary_wrapper %>% 
  mutate(cluster_label = ordered(cluster_label, levels = str_remove_all(names(clrs$cluster_label$Ovarian.cancer.super), "\\.cell")))

plot_data_summary_site <- plot_data_pw %>%
  group_by(cluster_label, tumor_megasite, pathway) %>%
  pathway_summary_wrapper %>% 
  mutate(cluster_label = ordered(cluster_label, levels = str_remove_all(names(clrs$cluster_label$Ovarian.cancer.super), "\\.cell")))

plot_data_summary_mutsig_patient <- plot_data_pw %>% 
  group_by(consensus_signature, patient_id_short, pathway) %>% 
  pathway_summary_wrapper

plot_data_summary_mutsig_sample <- plot_data_pw %>% 
  group_by(consensus_signature, sample, pathway) %>% 
  pathway_summary_wrapper


```

```{r chunk_320_160, fig.width=11, fig.height=3.9}

common_heat_layers <- list(
  scale_fill_gradient2(low = scales::muted("blue"), high = scales::muted("red"), 
                       na.value = "grey10", 
                       breaks = c(-cut_value, 0, cut_value), 
                       labels = c(paste0("≤-", cut_value), "0", paste0("≥", cut_value)),
                       limits = c(-cut_value, cut_value)),
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
        axis.ticks = element_blank(),
        axis.line = element_blank(),
        axis.title = element_blank(),
        plot.margin = margin(0, 0, 0, 0),
        axis.text.y = element_blank(),
        legend.position = "top", 
        legend.justification = "center"),
  guides(fill = guide_colorbar(title.position = "top"))
)

pw_mean_score <- filter(plot_data_summary_site, pathway %in% all_pws_short)$mean_score

pw_breaks <- c(seq(min(pw_mean_score), 0, length.out = 5)[-5], 
               0, seq(0, max(pw_mean_score), length.out = 5)[-1])

rdbu <- rev(RColorBrewer::brewer.pal(7, "RdBu"))

pw_plot1 <- plot_data_summary_site %>% 
  mutate(facet_helper = "") %>% 
  filter(!str_detect(pathway, "module|HLA|B2M|CD274")) %>% 
  # filter(tumor_supersite %in% sois) %>% 
  ggplot() +
  geom_tile(aes(pathway, cluster_label, fill = mean_score)) +
  common_heat_layers +
  facet_wrap(~tumor_megasite, nrow = 1) + 
  labs(x = "Cluster", y = "Pathway", fill = "Mean\nPROGENy  \nscore") +
  scale_fill_gradientn(colours = rdbu, 
                       values = scales::rescale(pw_breaks),
                       breaks = c(-0.5, 0.5, 1.5),  
                       na.value = "grey10")

pw_plot1_anno <- plot_data_summary_site %>% 
  filter(!str_detect(pathway, "module")) %>% 
  # filter(tumor_supersite %in% sois[1]) %>% 
  mutate(tumor_megasite = case_when(
    tumor_megasite == "Adnexa" ~ " ",
    # tumor_megasite == "Ascites" ~ "  ",
    T ~ " "
  )) %>% 
  distinct(cluster_label, tumor_megasite, .keep_all = T) %>% 
  ggplot() +
  geom_tile(aes(tumor_megasite, cluster_label, fill = cluster_label)) +
  geom_point(aes(tumor_megasite, cluster_label), color = "white", alpha = 0.5, size = 5) +
  geom_text(aes(tumor_megasite, cluster_label, label = as.numeric(cluster_label))) +
  common_heat_layers + 
  scale_fill_manual(values = clrs$cluster_label$Ovarian.cancer.super %>% setNames(str_remove_all(names(.), "\\.cell"))) +
  facet_wrap(~tumor_megasite, ncol = 1, scales = "free_x") +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_text()) +
  guides(fill = F)

pw_heat_grid <- plot_grid(pw_plot1_anno, pw_plot1 + remove_guides, ncol = 2, align = "h", axis = "tb", rel_widths = c(0.16, 0.84))

ggdraw() +
  draw_plot(pw_heat_grid, width = 1, height = 0.85, x = 0, y = 0.15) +
  draw_plot(get_legend(pw_plot1), x = -0.42, y = -0.3)

ggsave("figures/320_cancer_cell_plotting_umap/003_pathway_heatmap.pdf", width = 11, height = 3.9)
ggsave("figures/320_cancer_cell_plotting_umap/003_pathway_heatmap.png", width = 11, height = 3.9)

```

[figures/320_cancer_cell_plotting_umap/003_pathway_heatmap.pdf](figures/320_cancer_cell_plotting_umap/003_pathway_heatmap.pdf)

[figures/320_cancer_cell_plotting_umap/003_pathway_heatmap.png](figures/320_cancer_cell_plotting_umap/003_pathway_heatmap.png)


```{r chunk_320_170, fig.width=6, fig.height=4}

hla_plot1 <- plot_data_summary_site %>% 
  mutate(facet_helper = "") %>% 
  filter(str_detect(pathway, "HLA|B2M")) %>% 
  # filter(tumor_supersite %in% sois) %>% 
  ggplot() +
  geom_tile(aes(pathway, cluster_label, fill = mean_score)) +
  common_heat_layers +
  facet_wrap(~tumor_megasite, nrow = 1) + 
  labs(x = "Cluster", y = "Pathway", fill = "Expression") +
  scale_fill_gradientn(colours = rdbu, 
                       values = scales::rescale(pw_breaks),
                       na.value = "grey10")

hla_heat_grid <- plot_grid(pw_plot1_anno, hla_plot1 + remove_guides, nrow = 1, align = "h", axis = "tb", rel_widths = c(0.3, 0.7))

ggdraw() +
  draw_plot(hla_heat_grid, width = 1, height = 0.85, x = 0, y = 0.15) +
  draw_plot(get_legend(hla_plot1), x = -0.34, y = -0.26)

ggsave("figures/320_cancer_cell_plotting_umap/003_hla_heatmap.pdf", width = 6, height = 4)
ggsave("figures/320_cancer_cell_plotting_umap/003_hla_heatmap.png", width = 6, height = 4)

```

[figures/320_cancer_cell_plotting_umap/003_hla_heatmap.pdf](figures/320_cancer_cell_plotting_umap/003_hla_heatmap.pdf)

[figures/320_cancer_cell_plotting_umap/003_hla_heatmap.pdf](figures/320_cancer_cell_plotting_umap/003_hla_heatmap.pdf)

```{r chunk_320_175, fig.width=10, fig.height=5}
              
# comparison_data_pw <- filter(plot_data_summary_mutsig_sample, pathway %in% str_remove_all(pois, "\\.pathway")) %>% 
#   mutate(pathway = ordered(pathway, levels = str_remove_all(pois, "\\.pathway"))) %>% 
#   rename(score = mean_score) %>% 
#   ungroup
# 
# pw_boxplot_mutsig_pw <- filter(plot_data_pw, pathway %in% str_remove_all(pois, "\\.pathway")) %>% 
#   mutate(pathway = ordered(pathway, levels = str_remove_all(pois, "\\.pathway"))) %>% 
#   ggplot(aes(consensus_signature, score)) +
#   geom_violin(aes(consensus_signature, score, fill = consensus_signature), color = "white", adjust = 2, alpha = 0.5, width = 1.5) +
#   geom_boxplot(aes(consensus_signature, score, color = consensus_signature),
#                width = 0.5, size = 0.75, outlier.shape = NA) +
#   geom_boxplot(aes(consensus_signature, score, fill = consensus_signature),
#                color = "white", width = 0.5, outlier.shape = NA, size = 0.5) +
#   stat_compare_means(aes(consensus_signature, score, color = "red"), 
#                      ref.group = ".all.", data = comparison_data_pw,
#                      label = "p.signif", label.y = 3.5, hide.ns = T) +
#   # stat_pvalue_manual(test_result_jakstat, label = "p.adj") +
#   stat_compare_means(aes(consensus_signature, score),
#                      data = comparison_data_pw,
#                      label.y = 4.3, label.x = 1.5, label.sep = "\n\n") +
#   facet_wrap(~pathway) +
#   scale_color_manual(values = clrs$consensus_signature) +
#   scale_fill_manual(values = clrs$consensus_signature) +
#   theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)) +
#   labs(x = "", y = "PROGENy score") +
#   coord_cartesian(ylim = c(-1, 5))

# comparison_data_module <- filter(plot_data_summary_mutsig_sample, pathway %in% c("IFNg.signaling.module", "ISG.module")) %>% 
#   mutate(pathway = c(`IFNg.signaling.module` = "IFNg", `ISG.module` = "IFNa")[pathway]) %>% 
#   rename(score = mean_score)
# 
# pw_boxplot_mutsig_module <- filter(plot_data, pathway %in% c("IFNg.signaling.module", "ISG.module")) %>% 
#   mutate(pathway = c(`IFNg.signaling.module` = "IFNg", `ISG.module` = "IFNa")[pathway]) %>%  
#   ggplot(aes(consensus_signature, score)) +
#   geom_violin(aes(consensus_signature, score, fill = consensus_signature), color = "white", adjust = 2, alpha = 0.5, width = 1.5) +
#   geom_boxplot(aes(consensus_signature, score, color = consensus_signature),
#                width = 0.5, size = 0.75, outlier.shape = NA) +
#   geom_boxplot(aes(consensus_signature, score, fill = consensus_signature),
#                color = "white", width = 0.5, outlier.shape = NA, size = 0.5) +
#   stat_compare_means(aes(consensus_signature, score), 
#                      ref.group = ".all.", data = comparison_data_module,
#                      label = "p.signif", label.y = 0.9, hide.ns = T) +
#   stat_compare_means(aes(consensus_signature, score),
#                      data = comparison_data_module,
#                      label.y = 1.1, label.x = 1.5, label.sep = "\n\n") +
#   facet_wrap(~pathway) +
#   scale_color_manual(values = clrs$consensus_signature) +
#   scale_fill_manual(values = clrs$consensus_signature) +
#   theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)) +
#   labs(x = "", y = "Module score") +
#   coord_cartesian(ylim = c(-0.5, 1.2))
# 
# plot_box_grid <- plot_grid(pw_boxplot_mutsig_jakstat + remove_guides, 
#                            pw_boxplot_mutsig_module + remove_guides, 
#                            nrow = 1, align = "h", 
#                            rel_widths = c(c(0.37, 0.63)))


# pw_grid_full <- ggdraw() +
#   draw_plot(pw_grid_left, x = 0.01, y = 0, width = 0.41, height = 1) +
#   draw_plot(pw_boxplot_mutsig_pw + remove_guides, x = 0.46, y = 0, width = 0.4, height = 1)
# 
# pw_grid_full
# 
# ggsave("figures/320_cancer_cell_plotting_umap/003_pathway_heatmap_boxplot.pdf", pw_grid_full, 
#        width = 10, height = 5)
# 
# ggsave("figures/320_cancer_cell_plotting_umap/003_pathway_heatmap_boxplot.png", pw_grid_full, 
#        width = 10, height = 5)


```



## CD274 grid main text

```{r chunk_320_110, fig.width=3, fig.height=2}

# cd274_pos_frac <- plot_data_pw %>% 
#   filter(pathway == "CD274", consensus_signature %in% mois) %>% 
#   group_by(sample_id, patient_id_short, consensus_signature) %>% 
#   mutate(n = score > 0) %>% 
#   summarise(frac_pos = sum(n)/length(n)) %>% 
#   group_by(patient_id_short) %>% 
#   mutate(frac_pos_mean = mean(frac_pos, na.rm = T),
#          frac_pos_sd = sd(frac_pos, na.rm = T),
#          frac_pos_upper = frac_pos_mean + frac_pos_sd,
#          frac_pos_lower = frac_pos_mean - frac_pos_sd) %>% 
#   distinct(patient_id_short, .keep_all = T) %>% 
#   select(-sample_id) %>% 
#   ungroup() %>% 
#   arrange(frac_pos_mean) %>% 
#   mutate(patient_id_short = ordered(patient_id_short, levels = unique(patient_id_short)))
# 
# ggplot(cd274_pos_frac) +
#   geom_bar(aes(patient_id_short, frac_pos_mean, fill = consensus_signature),
#            stat = "identity") +
#   scale_fill_manual(values = clrs$consensus_signature) + 
#   theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))


```

```{r chunk_320_120, fig.width=7, fig.height=3.5}

violins_cd274_cluster <- violin_wrapper(cluster_label, "Cluster", "CD274", ".all.", "Expression", c(0,0.2), 10, site_filter = names(clrs$tumor_supersite), facet_site = F) + scale_y_continuous(breaks = c(0, 0.1, 0.2))
violins_cd274_mutsig <- violin_wrapper(consensus_signature, "Mutational\nsignature", "CD274", my_comparisons, "Expression", c(0, 0.2), 10, site_filter = names(clrs$tumor_supersite), facet_site = F) + scale_y_continuous(breaks = c(0, 0.1, 0.2))

umap_cd274_grid <- ggdraw() +
  draw_plot(add_umap_coord(umap_cd274, x_offset = -0.075, textsize = 3), 
            x = 0, y = 0.33, width = 0.4, height = 0.66) +
  draw_plot(plot_grid(violins_cd274_cluster, violins_cd274_mutsig, 
                      rel_widths = c(0.55, 0.45), align = "h"),
            x = 0.4, y = 0, width = 0.6, height = 1)

umap_cd274_grid

ggsave("figures/320_cancer_cell_plotting_umap/003_umap_cd274.pdf", 
       width = 7, height = 3.5)
ggsave("figures/320_cancer_cell_plotting_umap/003_umap_cd274.png", 
       width = 7, height = 3.5)

## pval

violins_cd274_cluster_pval <- violin_wrapper(cluster_label, "Cluster", "CD274", ".all.", "Expression", c(0,0.2), 10, "p.format", site_filter = names(clrs$tumor_supersite), facet_site = F) + scale_y_continuous(breaks = c(0, 0.1, 0.2))
violins_cd274_mutsig_pval <- violin_wrapper(consensus_signature, "Mutational\nsignature", "CD274", my_comparisons, "Expression", c(0, 0.2), 10, "p.format", site_filter = names(clrs$tumor_supersite), facet_site = F) + scale_y_continuous(breaks = c(0, 0.1, 0.2))

umap_cd274_grid_pval <- ggdraw() +
  draw_plot(add_umap_coord(umap_cd274, x_offset = -0.075, textsize = 3), 
            x = 0, y = 0.33, width = 0.4, height = 0.66) +
  draw_plot(plot_grid(violins_cd274_cluster_pval, violins_cd274_mutsig_pval, 
                      rel_widths = c(0.55, 0.45), align = "h"),
            x = 0.4, y = 0, width = 0.6, height = 1)

umap_cd274_grid_pval

ggsave("figures/320_cancer_cell_plotting_umap/003_umap_cd274_pval.pdf", 
           width = 7, height = 3.5)
ggsave("figures/320_cancer_cell_plotting_umap/003_umap_cd274_pval.png", 
           width = 7, height = 3.5)

```

## Violin grid supplement

```{r chunk_320_200, fig.width=7, fig.height=12}

pw_patient_boxplot_wrapper <- function(pw) {

  plot_data_pw_ranked_patients <- filter(plot_data_pw, pathway == pw) %>%
    # filter(patient_id_short %in% c("065", "054")) %>%
    group_by(patient_id_short) %>% 
    mutate(median = median(score)) %>%
    ungroup %>% 
    arrange(median) %>% 
    mutate(patient_id_short = ordered(patient_id_short, levels = unique(patient_id_short)))
  
  plot_data_pw_ranked_samples <- filter(plot_data_pw, pathway == pw) %>%
    # filter(patient_id_short %in% c("065", "054")) %>%
    group_by(sample) %>% 
    mutate(median = median(score),
           n = n()) %>%
    filter(n > 10) %>% 
    ungroup %>% 
    arrange(median) %>% 
    mutate(sample = ordered(sample, levels = unique(sample))) %>% 
    mutate(patient_id_short = ordered(patient_id_short, levels = levels(plot_data_pw_ranked_patients$patient_id_short)))
  
  plot_data_tumor_supersite_labels <- plot_data_pw_ranked_samples %>% 
    distinct(sample, .keep_all = T)
  
  upper_ylim <- filter(plot_data_pw, pathway == pw) %>% 
    # filter(patient_id_short %in% c("065", "054")) %>%
    group_by(sample) %>% 
    mutate(upper_whisker = 1.5*(quantile(score, 0.75) - quantile(score, 0.25))+quantile(score, 0.75)) %>% 
    pull(upper_whisker) %>% 
    unique %>% 
    max
  
  ggplot(plot_data_pw_ranked_samples) +
    # geom_violin(aes(patient_id_short, score, fill = consensus_signature), 
    #             color = "white", adjust = 2, alpha = 0.5, width = 1.5) +
    # geom_boxplot(aes(sample, score, color = consensus_signature),
    #              width = 0.5, size = 0.75, outlier.shape = NA) +
    geom_boxplot(aes(sample, score), fill = NA, 
                 width = 0.1, outlier.shape = NA, size = 0.5) +
    geom_boxplot(aes(sample, score, fill = consensus_signature), coef = 0,
                 outlier.shape = NA, size = 0.5, color = NA) +
    geom_point(aes(sample, median), color = "white", size = 0.35,
               data = plot_data_tumor_supersite_labels) +
    # geom_boxplot(aes(sample, score, color = consensus_signature), 
    #              width = 0.9, outlier.shape = NA, size = 0.5,
    #              fatten = NULL, fill = NA, coef = 0) +
    geom_point(aes(sample, color = tumor_supersite), 
               y = -2, size = 1.5, shape = 15,
               data = plot_data_tumor_supersite_labels) +
    geom_hline(aes(yintercept = median), alpha = 0.65,
               data = distinct(plot_data_pw_ranked_patients, 
                               patient_id_short, .keep_all = T)) +
    facet_grid(~patient_id_short, scales = "free_x", space = "free_x", 
               switch = "x") +
    scale_color_manual(values = clrs$tumor_supersite) +
    scale_fill_manual(values = clrs$consensus_signature) +
    theme(axis.text.x = element_blank(),
          # strip.placement = "outside",
          strip.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
          # strip.background = element_rect(color = "black", size = 0.1),
          axis.ticks.x = element_blank(),
          axis.line.x = element_blank(),
          plot.title = element_text(vjust = 0.5, hjust = 0.5, face = "plain"),
          panel.spacing = unit(2, "points")) +
    coord_cartesian(clip = "off") + 
    scale_y_continuous(limits = c(-2, upper_ylim), breaks = seq(-3, 9, by = 3)) +
    labs(x = "Patient", y = "PROGENy score",
         fill = "Mutational\nsignature",
         color = "Mutational\nsignature",
         title = str_remove_all(as_label(pw), '"'))

}

# pw_patient_boxplot_wrapper("TGFb") + remove_guides

pw_patient_plots_list <- lapply(str_remove_all(pois, ".pathway"), pw_patient_boxplot_wrapper) %>%
  # lapply(add, ylim(c(-1, 5))) %>%
  lapply(add, remove_guides)

hla_patient_plots_list <- lapply(gois, pw_patient_boxplot_wrapper) %>%
  lapply(add, remove_guides) %>%
  # lapply(add, ylim(c(-1, 5))) %>%
  lapply(add, labs(y = "Expression"))

pw_patient_plots_grid <- plot_grid(plotlist = pw_patient_plots_list, ncol = 1)
pw_patient_plots_grid

ggsave("figures/320_cancer_cell_plotting_umap/003_pathway_boxplot_patient_lvl.pdf",
       width = 9, height = 12)
ggsave("figures/320_cancer_cell_plotting_umap/003_pathway_boxplot_patient_lvl.png",
       width = 9, height = 12)

```

[figures/320_cancer_cell_plotting_umap/003_pathway_boxplot_patient_lvl.pdf](figures/320_cancer_cell_plotting_umap/003_pathway_boxplot_patient_lvl.pdf)

[figures/320_cancer_cell_plotting_umap/003_pathway_boxplot_patient_lvl.png](figures/320_cancer_cell_plotting_umap/003_pathway_boxplot_patient_lvl.png)

```{r chunk_320_220, fig.width=7, fig.height=16}

hla_patient_plots_grid <- plot_grid(plotlist = hla_patient_plots_list[-7], ncol = 1)
hla_patient_plots_grid

ggsave("figures/320_cancer_cell_plotting_umap/003_hla_boxplot_patient_lvl.pdf", 
            width = 9, height = 16)
ggsave("figures/320_cancer_cell_plotting_umap/003_hla_boxplot_patient_lvl.png", 
       width = 9, height = 16)

```

[figures/320_cancer_cell_plotting_umap/003_hla_boxplot_patient_lvl.pdf](figures/320_cancer_cell_plotting_umap/003_hla_boxplot_patient_lvl.pdf)

[figures/320_cancer_cell_plotting_umap/003_hla_boxplot_patient_lvl.png](figures/320_cancer_cell_plotting_umap/003_hla_boxplot_patient_lvl.png)


```{r chunk_320_240, fig.width=28, fig.height=30}

violin_grid_sub <- plot_grid(
  violins_pw_cluster + theme(plot.margin = margin(0.01, 0.1, 0.1, 0.01, "npc")), 
  violins_hla_cluster + theme(plot.margin = margin(0.01, 0.01, 0.01, 0.01, "npc")),
  violins_pw_mutsig_short + theme(plot.margin = margin(0.01, 0.4, 0.01, 0.01, "npc")),
  violins_hla_mutsig_short + theme(plot.margin = margin(0.01, 0.3, 0.01, 0.01, "npc")), 
  ncol = 2, align = "h", axis = "tb")

ggdraw() +
  draw_plot(pw_patient_plots_grid, x = 0.05, y = 0.52, width = 0.45, height = 0.45) +
  draw_plot(hla_patient_plots_grid, x = 0.52, y = 0.43, width = 0.45, height = 0.54) +
  draw_plot(violin_grid_sub, x = 0.05, y = 0.1, width = 0.9, height = 0.3)
  
ggsave("figures/320_cancer_cell_plotting_umap/003_suppl_violins_grid.pdf", width = 28, height = 30)

ggsave("figures/320_cancer_cell_plotting_umap/003_suppl_violins_grid.png", width = 28, height = 30)

```

[figures/320_cancer_cell_plotting_umap/003_suppl_violins_grid.pdf](figures/320_cancer_cell_plotting_umap/003_suppl_violins_grid.pdf)

[figures/320_cancer_cell_plotting_umap/003_suppl_violins_grid.png](figures/320_cancer_cell_plotting_umap/003_suppl_violins_grid.png)

## session info 

```{r chunk_320_999}

devtools::session_info()

```

