---
title: "MSK SPECTRUM data freeze: inferCNV"
author: "Florian Uhlitz"
date: "`r Sys.Date()`"
output: 
  html_document: 
    df_print: kable
    number_sections: yes
    toc: yes
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}

knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = F)

```

# InferCNV 

```{r chunk_360_010}

library(magrittr)
library(tidyverse)
library(Seurat)
library(readxl)
library(cowplot)
library(viridis)
library(ggpubr)
library(ggdendro)
library(dendextend)
library(infercnv)

```

```{r chunk_360_020}

## load global vars: 
source("src/global_vars.R")

# scrna_meta_tbl
# clrs
# markers_v7
# markers_v7_super
# cell_type_super_lookup

```

```{r chunk_360_040}

## load full seurat objects with expression data
seu_obj_cc <- read_rds("/work/shah/users/uhlitzf/data/SPECTRUM/freeze/v7/Ovarian.cancer.super_processed_filtered_annotated.rds")
marker_tbl <- read_tsv("/work/shah/users/uhlitzf/data/SPECTRUM/freeze/v7/supplementary_tables/Ovarian.cancer.super_marker_table_annotated.tsv")

marker_tbl_top <- marker_tbl %>% 
  filter(avg_logFC > 0.5, 
         p_val_adj < 0.01,
         pct.1 > 0.2,
         pct.2 < 0.8,
         !is.na(cluster_label)) %>% 
  group_by(cluster_label) %>% 
  slice(1:50)

myfeatures <- c("UMAP_1", "UMAP_2", "umapharmony_1", "umapharmony_2", "sample", "doublet", "nCount_RNA", "nFeature_RNA", "percent.mt", "doublet_score", "cell_type", "cell_id")

my_subtypes <- names(clrs$cluster_label$Ovarian.cancer.super)
coi <- "Ovarian.cancer.super"

mois <- c("HRD-Dup", "HRD-Del", "FBI")
gois <- c("HLA-A", "HLA-B", "HLA-C", "B2M", "HLA-DRA", "HLA-DRB1", "CD274")
sois <- c("Adnexa", "Omentum", "Ascites")
pois_short <- c("JAK.STAT", "NFkB", "TNFa", "TGFb", "Hypoxia")
pois <- paste0(pois_short, ".pathway")
all_pws <- grep("pathway", colnames(seu_obj_cc@meta.data), value = T)
all_pws_short <- str_remove_all(all_pws, "\\.pathway")
ptois <- c("007", "036", "107")


## load inferCNV outputs -------------------------------

inferCNV_dirs <- list.files("/work/shah/users/shih/infercnv_pipeline/data/infercnv", pattern = "20210709", full.names = T) %>% grep("SPECTRUM", ., value = T)

inferCNV_clone_files <- paste0(inferCNV_dirs, "/rand_tree_tumor_subcluters.csv")

inferCNV_clone_tbl <- lapply(inferCNV_clone_files, read_csv) %>% 
  bind_rows %>% 
  rename(clone_label = cluster_name)

clrs$clone_label <- magma(length(unique(inferCNV_clone_tbl$clone_label)))
names(clrs$clone_label) <- sort(unique(inferCNV_clone_tbl$clone_label))


## load BAF annotation -------------------------------

baf_tbl_full <- read_tsv("/work/shah/vazquezi/data/transfers/spectrum/results/scrna/v27/ascn/outputs/ascn/cell-type/Ovarian.cancer.cell.tsv")
baf_tbl <- baf_tbl_full %>% 
  filter(chrarm == "6p") %>% 
  group_by(patient) %>%
  mutate(UMAP_1_z = (UMAP_1 - mean(UMAP_1)) / sd(UMAP_2),
         UMAP_2_z = (UMAP_2 - mean(UMAP_2)) / sd(UMAP_2)) %>% 
  filter(UMAP_1_z < 3, UMAP_1_z > -3,
         UMAP_2_z < 3, UMAP_2_z > -3) %>% 
  ungroup() %>% 
  select(cell_id, UMAP_1, UMAP_2, BAF6p = BAF)


## single cell annotation ---------------------------

anno_data <- seu_obj_cc %>% 
  FetchData(c("sample", "cell_id", "cluster_label", "JAK.STAT.pathway", "NFkB.pathway", "TNFa.pathway", "TGFb.pathway", "Hypoxia.pathway")) %>%
  as_tibble() %>% 
  left_join(scrna_meta_tbl, by = "sample") %>% 
  left_join(inferCNV_clone_tbl, by = "cell_id") %>% 
  # filter(!is.na(clone_label)) %>%
  left_join(baf_tbl, by = "cell_id")

```

# UMAPs

## patients

```{r chunk_360_100}

anno_data_sub <- anno_data %>% 
  filter(patient_id %in% c("SPECTRUM-OV-036", "SPECTRUM-OV-007", "SPECTRUM-OV-107"))

p1 <- ggplot(anno_data_sub, aes(UMAP_1, UMAP_2, color = tumor_supersite)) + 
  ggrastr::geom_point_rast(size = 0.01, scale = 0.2, raster.dpi = 60) +
  facet_wrap(~patient_id_short, scales = "free", ncol = 1) +
  scale_color_manual(values = clrs$tumor_supersite) +
  remove_xaxis +
  remove_yaxis

p2 <- ggplot(anno_data_sub, aes(UMAP_1, UMAP_2, color = cluster_label)) + 
  ggrastr::geom_point_rast(size = 0.01, scale = 0.2, raster.dpi = 60) +
  facet_wrap(~patient_id_short, scales = "free", ncol = 1) +
  scale_color_manual(values = clrs$cluster_label$Ovarian.cancer.super) +
  remove_xaxis +
  remove_yaxis

p3 <- ggplot(anno_data_sub, aes(UMAP_1, UMAP_2, color = JAK.STAT.pathway)) + 
  ggrastr::geom_point_rast(size = 0.01, scale = 0.2, raster.dpi = 60) +
  facet_wrap(~patient_id_short, scales = "free", ncol = 1) +
  scale_color_viridis() +
  remove_xaxis +
  remove_yaxis

p4 <- ggplot(anno_data_sub) + 
  ggrastr::geom_point_rast(aes(UMAP_1, UMAP_2), color = "grey80", size = 0.01, 
                           scale = 0.2, raster.dpi = 60) +
  ggrastr::geom_point_rast(aes(UMAP_1, UMAP_2, color = clone_label), size = 0.5,
                           scale = 0.2, raster.dpi = 60,
                           data = filter(anno_data_sub, !is.na(clone_label))) +
  facet_wrap(~patient_id_short, scales = "free", ncol = 1) +
  scale_color_manual(values = clrs$clone_label) +
  remove_xaxis +
  remove_yaxis

p5 <- ggplot(anno_data_sub, aes(UMAP_1, UMAP_2, color = BAF6p)) + 
  ggrastr::geom_point_rast(size = 0.01, scale = 0.2, raster.dpi = 60) +
  facet_wrap(~patient_id_short, scales = "free", ncol = 1) +
  scale_color_viridis() +
  remove_xaxis +
  remove_yaxis

umap_grid <- plot_grid(p2 + remove_guides, p4 + remove_guides, ncol = 2, align = "hv")

```

# distributions 

```{r chunk_360_120, fig.width=6, fig.height=5}

## cell annotation
anno_data_sub <- anno_data %>% 
  filter(patient_id_short %in% ptois) %>% 
  filter(!is.na(clone_label)) %>% 
  group_by(patient_id_short, clone_label) %>% 
  mutate(ncells_clone = n()) %>% 
  group_by(patient_id_short, cluster_label) %>% 
  mutate(ncells_cluster = n()) %>% 
  ungroup() %>% 
  filter(ncells_clone > 50) %>%
  filter(ncells_cluster > 50) %>%
  mutate(stat_group_clone = paste0(patient_id_short, clone_label),
         stat_group_cluster = paste0(patient_id_short, cluster_label)) %>% 
  mutate(value = JAK.STAT.pathway)

# anno_data_test <- anno_data_sub %>% 
#   group_by(sample_id, patient_id_short, cluster_label) %>% 
#   summarise(value = mean(JAK.STAT.pathway)) %>% 
#   select(-sample_id) %>% 
#   ungroup()
# 
# anno_data_test

icnv_boxplot1 <- ggplot(anno_data_sub, aes(clone_label, value)) +
  geom_violin(aes(clone_label, value, color = clone_label)) +
  geom_boxplot(aes(clone_label, value, color = clone_label), outlier.shape = NA) +
  facet_wrap(~patient_id_short, ncol = 1) +
  stat_compare_means(ref.group = ".all.", hide.ns = T, label = "p.signif", method.args = list(alternative = "greater"), label.y.npc = 0.8, paired = F) +
  scale_color_manual(values = clrs$clone_label) +
  remove_xaxis +
  labs(y = "JAK.STAT PROGENy score")

icnv_boxplot2 <- ggplot(anno_data_sub, aes(cluster_label, value, group = cluster_label)) +
  geom_violin(aes(cluster_label, value, color = cluster_label, group = cluster_label)) +
  geom_boxplot(aes(cluster_label, value, color = cluster_label, group = cluster_label), outlier.shape = NA) +
  facet_wrap(~patient_id_short, ncol = 1) +
  stat_compare_means(ref.group = ".all.", hide.ns = T, label = "p.signif", method.args = list(alternative = "greater"), label.y.npc = 0.8, paired = F, data = select(anno_data_sub, cluster_label, value, patient_id_short)) +
  scale_color_manual(values = clrs$cluster_label$Ovarian.cancer.super) +
  remove_xaxis +
  labs(y = "JAK.STAT PROGENy score")

icnv_boxplot_grid <- plot_grid(icnv_boxplot1 + remove_guides, icnv_boxplot2 + remove_guides, ncol = 2)

icnv_boxplot_grid

```

# summary heatmaps

```{r chunk_360_140, fig.width=11.5, fig.height=4.5}

rdbu <- rev(RColorBrewer::brewer.pal(7, "RdBu"))
scale_breaks <- c(seq(-1, 0, length.out = 4)[-4], 0, seq(0, 3, length.out = 4)[-1])

heat_theme <- list(
  theme(
    axis.text.x = element_blank(),
    axis.line = element_blank(),
    axis.ticks = element_blank(),
    axis.title.x = element_blank(),
    plot.title = element_text(face = "plain", hjust = 0.5),
    plot.margin = margin(2, 2, 2, 2, "pt"),
  ),
  scale_fill_gradientn(colours = rdbu, 
                       values = scales::rescale(scale_breaks),
                       breaks = c(-1, 0, 1, 2, 3), 
                       limits = c(-1, 3),
                       na.value = "grey50")
)

anno_data_summary_jakstat <- anno_data %>% 
  filter(str_detect(cluster_label, "ancer")) %>% 
  group_by(patient_id_short) %>% 
  summarise(median_value = median(JAK.STAT.pathway, na.rm = T)) %>% 
  ungroup() %>% 
  arrange(desc(median_value)) %>% 
  mutate(patient_id_short = ordered(patient_id_short, levels = unique(patient_id_short)),
         yhelper = "Median JAK/STAT score")

anno_data_summary_cluster <- anno_data %>% 
  filter(str_detect(cluster_label, "ancer")) %>% 
  group_by(cluster_label, patient_id_short) %>% 
  summarise(median_value = median(JAK.STAT.pathway, na.rm = T)) %>% 
  ungroup() %>% 
  arrange(desc(cluster_label == "Cancer.cell.3"), desc(median_value)) %>% 
  mutate(patient_id_short = ordered(patient_id_short, levels = levels(anno_data_summary_jakstat$patient_id_short)))

anno_data_summary_clone <- anno_data %>% 
  filter(!is.na(clone_label)) %>% 
  ## collapse clones (cut tree earlier)
  mutate(clone_label = str_sub(clone_label, 0, 17)) %>%
  mutate(clone_label = ifelse(clone_label == "observation.1.2", "observation.1.2.1", clone_label)) %>%
  group_by(clone_label, patient_id_short) %>% 
  summarise(median_value = median(JAK.STAT.pathway, na.rm = T)) %>% 
  ungroup() %>% 
  mutate(patient_id_short = ordered(patient_id_short, levels = levels(anno_data_summary_jakstat$patient_id_short)))
  
anno_data_summary_mutsig <- anno_data %>% 
  distinct(patient_id_short, consensus_signature) %>% 
  mutate(patient_id_short = ordered(patient_id_short, levels = levels(anno_data_summary_jakstat$patient_id_short))) %>% 
  mutate(mutsig_helper = "Mut. signature")

anno_data_summary_fraction <- anno_data %>% 
  group_by(patient_id_short, cluster_label) %>% 
  tally %>% 
  group_by(patient_id_short) %>% 
  mutate(ntotal = sum(n),
         nrel = n/ntotal*100) %>% 
  ungroup() %>% 
  mutate(patient_id_short = ordered(patient_id_short, levels = levels(anno_data_summary_jakstat$patient_id_short)))

heat_clone <- ggplot(anno_data_summary_clone, aes(patient_id_short, clone_label, fill = median_value)) + 
  geom_tile() +
  labs(x = "Patient", y = "InferCNV\nClone", title = "JAK/STAT PROGENy score", fill = "JAK/STAT\nscore") +
  heat_theme

heat_cluster <- ggplot(anno_data_summary_cluster, aes(patient_id_short, cluster_label, fill = median_value)) + 
  geom_tile() +
  labs(x = "Patient", y = "Cluster", fill = "JAK/STAT\nscore") +
  heat_theme

heat_jakstat <- ggplot(anno_data_summary_jakstat, aes(patient_id_short, yhelper, fill = median_value)) + 
  geom_tile() +
  labs(x = "Patient", y = "", fill = "JAK/STAT\nscore") +
  heat_theme

heat_fraction <- filter(anno_data_summary_fraction, cluster_label == "Cancer.cell.3") %>% 
  mutate(cluster_label_helper = "Cancer.cell.3 frac. [%]") %>% 
  ggplot() +
  geom_tile(aes(patient_id_short, cluster_label_helper, fill = nrel)) +
  geom_text(aes(patient_id_short, cluster_label_helper, label = round(nrel, 0)), color = "white", size = 3) +
  remove_xaxis +
  scale_fill_gradientn(colors = viridis(9)) + 
  theme(axis.ticks = element_blank(),
        axis.line = element_blank(),
        axis.title = element_blank(), 
        plot.margin = margin(2, 2, 2, 2, "pt"))

heat_anno <- ggplot(anno_data_summary_mutsig, aes(patient_id_short, mutsig_helper, fill = consensus_signature)) +
  geom_tile() +
  labs(x = "Patient", y = "") +
  scale_fill_manual(values = clrs$consensus_signature[c(mois, "Undetermined")]) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5), 
        axis.ticks = element_blank(),
        axis.line = element_blank(),
        plot.margin = margin(2, 2, 2, 2, "pt"))

heat_grid <- plot_grid(
  heat_clone + remove_guides, 
  heat_cluster + remove_guides, 
  heat_jakstat + remove_guides, 
  heat_fraction + remove_guides,
  heat_anno + remove_guides, 
  ncol = 1, align = "v", 
  rel_heights = c(0.28, 0.38, 0.07, 0.07, 0.2)
)

ggdraw() +
  draw_plot(heat_grid, width = 0.85, height = 1) +
  draw_grob(get_legend(heat_cluster), x = 0.87, y = 0)

ggsave("figures/360_cancer_cell_infercnv_umaps/360_JAKSTAT_heatmap.pdf", width = 11.5, height = 4.5)

```


# main text grid

```{r chunk_360_150, fig.width=12, fig.height=5}

icnv_grid <- ggdraw() +
  draw_plot(umap_grid, width = 0.3, height = 1, x = 0.3, y = 0) +
  draw_plot(icnv_boxplot_grid, width = 0.4, height = 1, x = 0.6, y = 0)

icnv_grid
ggsave("figures/360_cancer_cell_infercnv_umaps/icnv_grid.pdf", width = 8, height = 3)

```



## session info 

```{r chunk_360_999}

devtools::session_info()

```

