---
title: "MSK SPECTRUM data freeze: AMP status expression"
author: "Florian Uhlitz"
date: "`r Sys.Date()`"
output: 
  html_document: 
    df_print: kable
    number_sections: yes
    toc: yes
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}

knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = F)

```

# InferCNV 

```{r chunk_360_010}

library(magrittr)
library(tidyverse)
library(Seurat)
library(readxl)
library(cowplot)
library(viridis)
library(ggpubr)

```

```{r chunk_360_020}

## load global vars: 
source("src/global_vars.R")

# scrna_meta_tbl
# clrs
# markers_v7
# markers_v7_super
# cell_type_super_lookup

```

```{r chunk_360_040}

## load full seurat objects with expression data
seu_obj_cc <- read_rds("/work/shah/users/uhlitzf/data/SPECTRUM/freeze/v7/Ovarian.cancer.super_processed_filtered_annotated.rds")

colnames(impact_meta_tbl)

colnames(scrna_meta_tbl)

myfeatures <- c("UMAP_1", "UMAP_2", "umapharmony_1", "umapharmony_2", "sample", "doublet", "nCount_RNA", "nFeature_RNA", "percent.mt", "doublet_score", "cell_type", "cell_id")

my_subtypes <- names(clrs$cluster_label$Ovarian.cancer.super)
coi <- "Ovarian.cancer.super"

mois <- c("HRD-Dup", "HRD-Del", "FBI")
gois <- c("HLA-A", "HLA-B", "HLA-C", "B2M", "HLA-DRA", "HLA-DRB1", "CD274")
sois <- c("Adnexa", "Omentum", "Ascites")
pois_short <- c("JAK.STAT", "NFkB", "TNFa", "TGFb", "Hypoxia")
pois <- paste0(pois_short, ".pathway")
all_pws <- grep("pathway", colnames(seu_obj_cc@meta.data), value = T)
all_pws_short <- str_remove_all(all_pws, "\\.pathway")


```

## session info 

```{r chunk_360_999}

devtools::session_info()

```

