---
title: "MSK SPECTRUM freeze CD8 T cells"
author: "Florian Uhlitz"
date: "`r Sys.Date()`"
output: 
  html_document: 
    df_print: kable
    number_sections: yes
    toc: yes
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}

knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = F)

```

# Figure 5 lower

```{r chunk_520_010}

library(magrittr)
library(tidyverse)
library(Seurat)
library(readxl)
library(cowplot)
library(colorblindr)
library(viridis)
library(ComplexHeatmap)
library(grid)
library(ggpubr)

coi <- "T.super"
cell_sort <- "CD45+"
cell_type_major <- "T.cell"
louvain_resolution <- 0.3
louvain_cluster <- "RNA_snn_res.0.3"
pcut <- 0.05
mois <- c("HRD-Dup", "HRD-Del", "FBI")

```

```{r chunk_520_020}

## load global vars: 
source("src/global_vars.R")

# scrna_meta_tbl
# clrs
# markers_v7
# markers_v7_super
# cell_type_super_lookup

```

```{r chunk_520_030}

seu_obj_cd8_sub <- read_rds("/work/shah/users/uhlitzf/data/SPECTRUM/freeze/v7/CD8.T_processed_filtered.rds")

seu_obj_cc <- read_rds("/work/shah/users/uhlitzf/data/SPECTRUM/freeze/v7/Ovarian.cancer.super_processed_filtered_annotated.rds")

# seu_obj_ml <- read_rds("/work/shah/users/uhlitzf/data/SPECTRUM/freeze/v7/Myeloid.super_processed_filtered_annotated.rds")

module_names <- grep("pathway|CD8", colnames(seu_obj_cd8_sub@meta.data), value = T)

gois <- c("TCF7", "LEF1", "GZMK", "ISG15", "CXCL13", "TOX", "PDCD1")
gois_sub <- c("LEF1", "GZMK", "ISG15", "CXCL13")

module_names_sub <- c("CD8.Naive.module", "CD8.Cytotoxic.module", "CD8.Predysfunctional.module", "CD8.Dysfunctional.module", "JAK.STAT.pathway")

myfeatures <- c("cell_id", "umapharmony_1", "umapharmony_2", "sample", "DC_1", "DC_2", "DPT1",  "cell_type", "cluster_label_sub")

my_subtypes <- names(clrs$cluster_label_sub[[coi]])

plot_data <- as_tibble(FetchData(seu_obj_cd8_sub, c(myfeatures, module_names, gois))) %>%
  # mutate(DC_1 = -DC_1, DC_2 = -DC_2) %>% 
  mutate(DC_1 = -DC_1, DC_2 = DC_2) %>% 
  gather(key, value, -c(1:length(myfeatures))) %>% 
  left_join(scrna_meta_tbl, by = "sample") %>%
  mutate(cell_type_super = cell_type_super_lookup[cell_type]) %>%
  mutate(sort_short_x = ifelse(sort_short == "U" & cell_type_super == "Immune",
                               "CD45+", ifelse(sort_short == "U" & cell_type_super == "Stromal", "CD45-", sort_short))) %>% 
  mutate(cluster_label_sub = ordered(cluster_label_sub, levels = my_subtypes))

plot_data_uniq <- distinct(plot_data, cell_id, .keep_all = T)

```

## CD8 T cell diffusion map

```{r chunk_520_120, fig.width=10, fig.height=5}

arrow <- arrow(angle = 20, type = "closed", length = unit(0.1, "npc"))
umap_coord_anno <- ggplot(tibble(group = c("DC1", "DC2"),
                                 x = c(0, 0), xend = c(1, 0),
                                 y = c(0, 0), yend = c(0, 1),
                                 lx = c(0.5, -0.15), ly = c(-0.15, 0.5),
                                 angle = c(0, 90))) +
  geom_segment(aes(x, y, xend = xend, yend = yend, group = group),
               arrow = arrow, size = 1, lineend = "round") +
  geom_text(aes(lx, ly, label = group, angle = angle), size = 4) +
  theme_void() +
  coord_fixed(xlim = c(-0.3, 1), ylim = c(-0.3, 1))

add_umap_coord <- function(gg_obj) {
  p <- ggdraw() + 
    draw_plot(gg_obj, x = 0, y = 0, width = 1, height = 1) +
    draw_plot(umap_coord_anno, x = -0.015, y = -0.02, width = 0.4, height = 0.4)
  return(p)
}

rdpi <- 75
rscale <- 0.5
rs <- 0.01

dc_plot_cluster <- ggplot(plot_data_uniq) +
  ggrastr::geom_point_rast(aes(DC_1, DC_2, color = cluster_label_sub), 
                           size = rs, alpha = 1, 
                           raster.dpi = rdpi, scale = rscale) +
  # theme_void() +
  scale_color_manual(values = clrs$cluster_label_sub[[coi]][str_detect(names(clrs$cluster_label_sub[[coi]]), "^CD8")]) +
  guides(color = guide_legend(override.aes = list(size = 3, alpha = 1))) +
  theme(aspect.ratio = 1,
        axis.line = element_blank(),
        axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank()) + 
  labs(color = "Cluster")

# dc_plot_cluster_cxcl13 <- ggplot() +
#   ggrastr::geom_point_rast(aes(DC_1, DC_2), color = "grey80", 
#                            size = 0.01, alpha = 0.1, raster.dpi = 75, 
#                            data = plot_data_uniq) +
#   ggrastr::geom_point_rast(aes(DC_1, DC_2, color = cluster_label_sub), 
#                            size = 0.01, alpha = 0.1, raster.dpi = 75,
#                            data = filter(plot_data_uniq, cluster_label_sub != "CD8.T.ISG")) +
#   theme_void() +
#   scale_color_manual(values = clrs$cluster_label_sub[[coi]], guide = F) +
#   theme(aspect.ratio = 1)
# 
# dc_plot_cluster_isg <- ggplot() +
#   ggrastr::geom_point_rast(aes(DC_1, DC_2), color = "grey80", 
#                            size = 0.01, alpha = 0.1, raster.dpi = 75, 
#                            data = plot_data_uniq) +
#   ggrastr::geom_point_rast(aes(DC_1, DC_2, color = cluster_label_sub), 
#                            size = 0.01, alpha = 0.1, raster.dpi = 75,
#                            data = filter(plot_data_uniq, cluster_label_sub != "CD8.T.CXCL13")) +
#   theme_void() +
#   scale_color_manual(values = clrs$cluster_label_sub[[coi]], guide = F) +
#   theme(aspect.ratio = 1)


dc_plot_dpt <- ggplot(plot_data_uniq) +
  ggrastr::geom_point_rast(aes(DC_1, DC_2, color = DPT1), size = rs, alpha = 1, 
                           raster.dpi = rdpi, scale = rscale) +
  theme_void() +
  scale_color_gradientn(colors = plasma(9)) +
  theme(aspect.ratio = 1) +
  labs(color = "Pseudotime")

dc_plot_cxcl13 <- ggplot(filter(plot_data, key == "CXCL13")) +
  ggrastr::geom_point_rast(aes(DC_1, DC_2, color = value), size = rs, alpha = 1,
                           raster.dpi = 75) +
  theme_void() +
  scale_color_gradientn(colors = viridis(9), breaks = c(0, 6), labels = c("low", "high")) +
  theme(aspect.ratio = 1) +
  labs(color = "Expression", title = "CXCL13")

dc_plot_isg <- ggplot(filter(plot_data, key == "ISG15")) +
  ggrastr::geom_point_rast(aes(DC_1, DC_2, color = value), size = rs, alpha = 1,
                           raster.dpi = 75) +
  theme(axis.text = element_blank(),
        axis.title = element_blank(),
        axis.line = element_blank(),
        axis.ticks = element_blank()) +
  scale_color_gradientn(colors = viridis(9)) +
  theme(aspect.ratio = 1) +
  labs(color = "Expression", title = "ISG15")

dc_plot_genes <- ggplot() +
  # ggrastr::geom_point_rast(aes(DC_1, DC_2), color = "grey80", size = 0.1, alpha = 1,
  #                          raster.dpi = 75, 
  #                          data = filter(plot_data, key %in% gois, value == 0)) +
  # ggrastr::geom_point_rast(aes(DC_1, DC_2, color = value), size = 0.1, alpha = 1,
  #                          raster.dpi = 75,
  #                          data = filter(plot_data, key %in% gois, value > 0)) +
  ggrastr::geom_point_rast(aes(DC_1, DC_2), color = "grey80", size = rs, alpha = 1,
                           raster.dpi = rdpi, scale = rscale,
                           data = filter(plot_data, key %in% gois_sub, value == 0) %>% 
                             mutate(key = ordered(key, levels = gois_sub))) +
  ggrastr::geom_point_rast(aes(DC_1, DC_2, color = value), size = rs, alpha = 1,
                           raster.dpi = rdpi, scale = rscale,
                           data = filter(plot_data, key %in% gois_sub, value > 0) %>% 
                             mutate(key = ordered(key, levels = gois_sub))) +
  facet_wrap(~key) + 
  theme(axis.text = element_blank(),
        axis.title = element_blank(),
        axis.line = element_blank(),
        axis.ticks = element_blank()) +  
  scale_color_gradientn(colors = viridis(9), breaks = c(0, 6), 
                        labels = c("low", "high")) +
  theme(aspect.ratio = 1) +
  labs(color = "Expression")

plot_data_cd8 <- filter(plot_data, str_detect(key, "CD8"))

dc_plot_mutsig <- ggplot() +
  geom_point(aes(DC_1, DC_2), color = "grey80", size = 0.1, data = select(plot_data_cd8, -consensus_signature)) +
  geom_point(aes(DC_1, DC_2, color = value), size = 0.1, data = plot_data_cd8) +
  theme_void() +
  theme(strip.text.y = element_text(angle = 90)) +
  facet_grid(key~consensus_signature, switch = "y") + 
  scale_color_gradientn(colors = viridis(9), guide = F) +
  theme(aspect.ratio = 1) +
  labs(color = "Expression")

```

## CD8 T module curves

```{r chunk_520_130, fig.width=6, fig.height=4}

plot_data_smooth_wrapper <- function(...) {
  group_vars <- enquos(...)
  plot_data %>% 
    # filter(key %in% "TCF7") %>%
    # sample_n(10000) %>%
    group_by(!!!group_vars) %>%
    arrange(DPT1) %>%
    mutate(DPT1_bin = as.numeric(cut_number(DPT1, 10000))) %>%
    group_by(!!!group_vars, DPT1_bin) %>%
    mutate(mean_value = mean(value)) %>%
    distinct(!!!group_vars, DPT1_bin, .keep_all = T) %>%
    group_by(!!!group_vars) %>%
    do(fit = {
      loess(mean_value ~ DPT1_bin, data = .) %>%
        predict(se = T) %>%
        as_tibble() %>%
        mutate(DPT1_bin = row_number())
    }) %>%
    unnest(fit) %>%
    group_by(!!!group_vars) %>%
    mutate(scaled_value = scales::rescale(fit),
           se_upper = scaled_value+scaled_value/fit*se.fit,
           se_lower = scaled_value-scaled_value/fit*se.fit)
}

# plot_data_smooth <- plot_data_smooth_wrapper(key)
# write_tsv(plot_data_smooth, "/work/shah/users/uhlitzf/data/SPECTRUM/freeze/v7/CD8.T_fitted_module_curves.tsv")
plot_data_smooth <- read_tsv("/work/shah/users/uhlitzf/data/SPECTRUM/freeze/v7/CD8.T_fitted_module_curves.tsv")

# plot_data_smooth_megasite <- plot_data_smooth_wrapper(key, tumor_megasite) %>%
#   group_by(key) %>%
#   mutate(scaled_value = scales::rescale(fit),
#            se_upper = scaled_value+scaled_value/fit*se.fit,
#            se_lower = scaled_value-scaled_value/fit*se.fit) %>%
#   group_by(tumor_megasite) %>%
#   mutate(DPT1_bin = scales::rescale(DPT1_bin)) %>%
#   ungroup()
# write_tsv(plot_data_smooth_megasite, "/work/shah/users/uhlitzf/data/SPECTRUM/freeze/v7/CD8.T_fitted_module_curves_megasite.tsv")
plot_data_smooth_megasite <- read_tsv("/work/shah/users/uhlitzf/data/SPECTRUM/freeze/v7/CD8.T_fitted_module_curves_megasite.tsv")

# plot_data_smooth_mutsig <- plot_data_smooth_wrapper(key, consensus_signature) %>%
#   group_by(key) %>%
#   mutate(scaled_value = scales::rescale(fit),
#            se_upper = scaled_value+scaled_value/fit*se.fit,
#            se_lower = scaled_value-scaled_value/fit*se.fit) %>%
#   group_by(consensus_signature) %>%
#   mutate(DPT1_bin = scales::rescale(DPT1_bin)) %>%
#   ungroup()
# write_tsv(plot_data_smooth_mutsig, "/work/shah/users/uhlitzf/data/SPECTRUM/freeze/v7/CD8.T_fitted_module_curves_mutsig.tsv")
plot_data_smooth_mutsig <- read_tsv("/work/shah/users/uhlitzf/data/SPECTRUM/freeze/v7/CD8.T_fitted_module_curves_mutsig.tsv")

# plot_data_smooth_site <- plot_data_smooth_wrapper(key, tumor_supersite) %>%
#   group_by(key) %>%
#   mutate(scaled_value = scales::rescale(fit),
#            se_upper = scaled_value+scaled_value/fit*se.fit,
#            se_lower = scaled_value-scaled_value/fit*se.fit) %>%
#   group_by(tumor_supersite) %>%
#   mutate(DPT1_bin = scales::rescale(DPT1_bin)) %>%
#   ungroup()
# write_tsv(plot_data_smooth_site, "/work/shah/users/uhlitzf/data/SPECTRUM/freeze/v7/CD8.T_fitted_module_curves_site.tsv")
plot_data_smooth_site <- read_tsv("/work/shah/users/uhlitzf/data/SPECTRUM/freeze/v7/CD8.T_fitted_module_curves_site.tsv")

```

```{r chunk_520_135, fig.width=6, fig.height=4}

module_curves_module <- plot_data_smooth %>% 
  filter(key %in% module_names_sub) %>%
  mutate(key = ordered(str_remove_all(key, ".module"), 
                       levels = names(clrs$expression_module))) %>% 
  ggplot() +
  geom_line(aes(DPT1_bin, scaled_value, color = key), size = 1.5)+
  labs(x = "Pseudotime", y = "Scaled module score", color = "Module") +
  scale_color_manual(values = clrs$expression_module) +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(),
        legend.position = "bottom") +
  guides(color = guide_legend(override.aes = list(fill = NA), ncol = 2)) +
  scale_y_continuous(breaks = c(0, 1))

module_curves_module
ggsave("figures/520_T_cell_CD8_diffusion/005_pseudotime_curves_modules.pdf", module_curves_module, width = 6, height = 4)
ggsave("figures/520_T_cell_CD8_diffusion/005_pseudotime_curves_modules.png", module_curves_module, width = 6, height = 4)

module_curves_gois <- plot_data_smooth %>% 
  filter(key %in% gois) %>%
  mutate(key = ordered(key, levels = gois)) %>% 
  ggplot() +
  geom_line(aes(DPT1_bin, scaled_value, color = key), size = 1.5) +
  # geom_line(aes(DPT1_bin, se_upper, color = key), size = 0.5, linetype = 2) +
  # geom_line(aes(DPT1_bin, se_lower, color = key), size = 0.5, linetype = 2) +
  labs(x = "Pseudotime", y = "Scaled gene expression", color = "Gene") +
  scale_color_manual(values = magma(length(gois)+1)[-(length(gois)+1)]) +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(),
        legend.position = "bottom") +
  guides(color = guide_legend(override.aes = list(fill = NA), ncol = 3)) +
  scale_y_continuous(breaks = c(0, 1))

module_curves_gois
ggsave("figures/520_T_cell_CD8_diffusion/005_pseudotime_curves_genes.pdf", module_curves_gois, width = 6, height = 4)
ggsave("figures/520_T_cell_CD8_diffusion/005_pseudotime_curves_genes.png", module_curves_gois, width = 6, height = 4)

```

```{r chunk_520_136, fig.width=8, fig.height=4}

module_curves_module_megasite <- plot_data_smooth_megasite %>% 
  filter(key %in% module_names_sub) %>%
  mutate(key = ordered(str_remove_all(key, ".module"), 
                       levels = names(clrs$expression_module))) %>% 
  ggplot() +
  geom_line(aes(DPT1_bin, scaled_value, color = tumor_megasite), size = 1.5) +
  labs(x = "Pseudotime", y = "Scaled module score", color = "Site") +
  facet_wrap(~key) + 
  scale_color_manual(values = clrs$tumor_supersite[c("Adnexa", "Ascites", "Other")]) +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(),
        aspect.ratio = 0.75) +
  guides(color = guide_legend(override.aes = list(fill = NA))) +
  scale_y_continuous(breaks = c(0, 1))

ggdraw() +
  draw_plot(module_curves_module_megasite + remove_guides) +
  draw_plot(get_legend(module_curves_module_megasite), x = 0.72, y = -0.2)

ggsave("figures/520_T_cell_CD8_diffusion/005_pseudotime_curves_megasite.pdf", width = 8, height = 4)
ggsave("figures/520_T_cell_CD8_diffusion/005_pseudotime_curves_megasite.png", width = 8, height = 4)

module_curves_module_site <- plot_data_smooth_site %>% 
  filter(key %in% module_names_sub) %>%
  filter(tumor_supersite %in% c("Adnexa", "Omentum", "Ascites")) %>% 
  mutate(key = ordered(str_remove_all(key, ".module"), 
                       levels = names(clrs$expression_module))) %>% 
  ggplot() +
  geom_line(aes(DPT1_bin, scaled_value, color = tumor_supersite), size = 1.5) +
  labs(x = "Pseudotime", y = "Scaled module score", color = "Site") +
  facet_wrap(~key) + 
  scale_color_manual(values = clrs$tumor_supersite[c("Adnexa", "Omentum", "Ascites")]) +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(),
        aspect.ratio = 0.75) +
  guides(color = guide_legend(override.aes = list(fill = NA))) +
  scale_y_continuous(breaks = c(0, 1))

ggdraw() +
  draw_plot(module_curves_module_site + remove_guides) +
  draw_plot(get_legend(module_curves_module_site), x = 0.72, y = -0.2)

ggsave("figures/520_T_cell_CD8_diffusion/005_pseudotime_curves_site.pdf", width = 8, height = 4)
ggsave("figures/520_T_cell_CD8_diffusion/005_pseudotime_curves_site.png", width = 8, height = 4)


module_curves_module_mutsig <- plot_data_smooth_mutsig %>% 
  filter(consensus_signature %in% mois) %>% 
  mutate(consensus_signature = ordered(consensus_signature, levels = names(clrs$consensus_signature))) %>% 
  filter(key %in% module_names_sub[c(1,4,5)]) %>%
  mutate(key = ordered(str_remove_all(key, ".module"), 
                       levels = names(clrs$expression_module))) %>% 
  ggplot() +
  geom_line(aes(DPT1_bin, scaled_value, color = consensus_signature), size = 1.5) +
  labs(x = "Pseudotime", y = "Scaled module score", color = "Signature") +
  facet_wrap(~key) + 
  scale_color_manual(values = clrs$consensus_signature[mois]) +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(),
        legend.position = "bottom", aspect.ratio = 1) +
  guides(color = guide_legend(override.aes = list(fill = NA), ncol = 4)) +
  scale_y_continuous(breaks = c(0, 1))

module_curves_module_mutsig

ggsave("figures/520_T_cell_CD8_diffusion/005_pseudotime_curves_mutsig.pdf", width = 8, height = 3)
ggsave("figures/520_T_cell_CD8_diffusion/005_pseudotime_curves_mutsig.png", width = 8, height = 3)


```

## violins  

```{r chunk_520_140, fig.width=4.5, fig.height=4}

mutsig_boxplot_data_full <- plot_data %>% 
  filter(key %in% module_names_sub) %>% 
  mutate(key = str_replace_all(key, "CD8\\.", "CD8\n")) %>% 
  mutate(key = str_replace_all(key, "JAK.STAT.pathway", "JAK/STAT\npathway")) %>% 
  mutate(key = str_replace_all(key, "ysfunctional", "ysfunct.")) %>% 
  mutate(key = str_remove_all(key, ".module")) %>% 
  mutate(key = ordered(key, levels = c("CD8\nNaive", "CD8\nPredysfunct.", "CD8\nCytotoxic", "CD8\nDysfunct.", "JAK/STAT\npathway")))

mutsig_boxplot_data <- plot_data %>% 
  filter(key %in% module_names_sub) %>% 
  filter(!(consensus_signature %in% c("Undetermined", "HRD"))) %>% 
  filter(tumor_supersite != "Ascites") %>% 
  mutate(tumor_megasite = str_replace_all(tumor_megasite, "Other", "Non-adnexa")) %>% 
  mutate(key = str_replace_all(key, "CD8\\.", "CD8\n")) %>% 
  mutate(key = str_replace_all(key, "JAK.STAT.pathway", "JAK/STAT\npathway")) %>% 
  mutate(key = str_replace_all(key, "ysfunctional", "ysfunct.")) %>% 
  mutate(key = str_remove_all(key, ".module")) %>% 
  mutate(key = ordered(key, levels = c("CD8\nNaive", "CD8\nPredysfunct.", "CD8\nCytotoxic", "CD8\nDysfunct.", "JAK/STAT\npathway")))

my_comparisons <- list(
  c("HRD-Dup", "HRD-Del"), 
  c("HRD-Dup", "FBI"), 
  c("HRD-Del", "FBI")
)

my_comparisons2 <- list(
  c("HRD", "HRP")
)

mutsig_boxplot_data_stats <- mutsig_boxplot_data %>% 
  group_by(sample, key) %>% 
  mutate(value = mean(value)) %>% 
  distinct(sample, key, .keep_all = T) %>% 
  ungroup()

violin_wrapper <- function(group_column, group_var_label, keys, comps, y_label, ylims) {
  group_column <- enquo(group_column)
  yrange <- ylims[2]-ylims[1]
  ylabels <- yrange*c(0.95,0.85,0.75)+ylims[1]
  mutsig_boxplot_data %>% 
    filter(key %in% keys) %>% 
    ggplot(aes(!!group_column, value)) +
    geom_violin(aes(!!group_column, value, fill = !!group_column), color = "white", adjust = 2, alpha = 0.5, width = 1.5) +
    geom_boxplot(aes(!!group_column, value, color = !!group_column),
                 width = 0.5, size = 0.75, outlier.shape = NA) +
    geom_boxplot(aes(!!group_column, value, fill = !!group_column),
                 color = "white", width = 0.5, outlier.shape = NA, size = 0.5) +
    stat_compare_means(comparisons = comps, 
                       data = filter(mutsig_boxplot_data_stats, 
                                     key %in% keys),
                       label = "p.signif", label.y = ylabels, 
                       hide.ns = F) +
    # stat_compare_means(ref.group = ".all.", 
    #                    data = filter(mutsig_boxplot_data_stats, 
    #                                  key != "JAK/STAT\npathway"),
    #                    label = "p.signif", label.y = 1.6, hide.ns = T) +
    # stat_compare_means(label.y = 1.9, label.x = 1.5, label.sep = "\n\n",
    #                    data = filter(mutsig_boxplot_data_stats, 
    #                                  key != "JAK/STAT\npathway")) +
    facet_wrap(~key, ncol = 5) +
    scale_color_manual(values = clrs[[as_label(group_column)]]) +
    scale_fill_manual(values = clrs[[as_label(group_column)]]) +
    theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
          axis.title.x = element_blank()) + 
    coord_cartesian(clip = "off", ylim = ylims) +
    labs(y = y_label, color = group_var_label, 
         fill = group_var_label)
}

boxplot_wrapper <- function(group_column, group_var_label, keys, comps, y_label, ylims, plabel = "p.signif", mut_filter = mois, site_filter = names(clrs$tumor_supersite), facet_site = T) {
  
  group_column <- enquo(group_column)
  yrange <- ylims[2]-ylims[1]
  ylabels <- yrange*c(0.85,0.75,0.65)+ylims[1]
  clrs$cluster_label <- clrs$cluster_label$Ovarian.cancer.super
  
  boxplot_data <- filter(mutsig_boxplot_data_stats, 
                         key %in% keys, 
                         consensus_signature %in% mut_filter,
                         tumor_supersite %in% site_filter,
                         tumor_megasite %in% c("Adnexa", "Non-adnexa"))
  
  p <- ggplot(boxplot_data, aes(!!group_column, value)) +
    geom_boxplot(aes(!!group_column, value, color = !!group_column),
                 width = 0.5, size = 0.75, outlier.shape = NA) +
    geom_boxplot(aes(!!group_column, value, fill = !!group_column),
                 color = "white", width = 0.5, outlier.shape = NA, size = 0.5) +
    geom_jitter(aes(!!group_column, value),
                color = "black", width = 0.15, size = 0.25, alpha = 0.5) +
    scale_color_manual(values = clrs[[as_label(group_column)]]) +
    scale_fill_manual(values = clrs[[as_label(group_column)]]) +
    theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
          axis.title.x = element_blank()) + 
    coord_cartesian(clip = "on", ylim = ylims) +
    labs(y = y_label, color = group_var_label, 
         fill = group_var_label) +
    remove_guides

  if (facet_site) {
    p <- p + facet_grid(tumor_megasite~key)
  } else {
    p <- p + facet_grid(~key)
  }
  
  if (any(unlist(comps) != ".all.")) {
    p <- p + 
      stat_compare_means(comparisons = comps, 
                         data = boxplot_data,
                         label = plabel, label.y = ylabels, 
                         tip.length = 0.01,
                         hide.ns = F)
  }
  
  if (all(unlist(comps) == ".all.")) {
    p <- p + 
      stat_compare_means(ref.group = ".all.", 
                         method.args = list(alternative = "greater"),
                         data = boxplot_data, 
                         label.y = ylabels[1], hide.ns = T,
                         label = plabel)
  }
  
  return(p)
  
}

```

```{r chunk_520_150, fig.width=4, fig.height=4}

mutsig_violin_cd8 <- violin_wrapper(consensus_signature, "Mutational\nsignature", c("CD8\nNaive", "CD8\nDysfunct."), my_comparisons, "Module score", c(-1,2))
mutsig_violin_cd8_short <- violin_wrapper(consensus_signature_short, "Mutational\nsignature", c("CD8\nNaive", "CD8\nDysfunct."), my_comparisons2, "Module score", c(-1,2))

mutsig_violin_jakstat <- violin_wrapper(consensus_signature, "Mutational\nsignature", c("JAK/STAT\npathway"), my_comparisons, "PROGENy score", c(-1,5))
mutsig_violin_jakstat_short <- violin_wrapper(consensus_signature_short, "Mutational\nsignature", c("JAK/STAT\npathway"), my_comparisons2, "PROGENy score", c(-1,5))


mutsig_violin_grid <- plot_grid(
  mutsig_violin_cd8 + guides(color = F, fill = F), 
  mutsig_violin_jakstat + guides(color = F, fill = F), 
  nrow = 1, rel_widths = c(0.62, 0.38)) 

mutsig_violin_grid

ggsave("figures/520_T_cell_CD8_diffusion/005_violins_mutsig.pdf", width = 4.5, height = 3)
ggsave("figures/520_T_cell_CD8_diffusion/005_violins_mutsig.png", width = 4.5, height = 3)

```

```{r chunk_520_160, fig.width=4, fig.height=4}

mutsig_violin_grid_short <- plot_grid(
  mutsig_violin_cd8_short + guides(color = F, fill = F), 
  mutsig_violin_jakstat_short + guides(color = F, fill = F), 
  nrow = 1, rel_widths = c(0.62, 0.38)) 

mutsig_violin_grid_short

ggsave("figures/520_T_cell_CD8_diffusion/005_violins_mutsig_short.pdf", width = 4, height = 3)
ggsave("figures/520_T_cell_CD8_diffusion/005_violins_mutsig_short.png", width = 4, height = 3)

```

```{r chunk_520_170, fig.width=5, fig.height=4.55}

mutsig_boxplot_cd8 <- boxplot_wrapper(consensus_signature, "Mutational\nsignature", c("CD8\nNaive", "CD8\nDysfunct."), my_comparisons, "Module score", c(-0.4,0.6))
mutsig_boxplot_cd8_short <- boxplot_wrapper(consensus_signature_short, "Mutational\nsignature", c("CD8\nNaive", "CD8\nDysfunct."), my_comparisons2, "Module score", c(-0.4,0.6))

mutsig_boxplot_jakstat <- boxplot_wrapper(consensus_signature, "Mutational\nsignature", c("JAK/STAT\npathway"), my_comparisons, "PROGENy score", c(-1,3))
mutsig_boxplot_jakstat_short <- boxplot_wrapper(consensus_signature_short, "Mutational\nsignature", c("JAK/STAT\npathway"), my_comparisons2, "PROGENy score", c(-1,3))

mutsig_boxplot_grid <- plot_grid(
  mutsig_boxplot_cd8 + guides(color = F, fill = F), 
  mutsig_boxplot_jakstat + guides(color = F, fill = F), 
  nrow = 1, rel_widths = c(0.62, 0.38)) 

mutsig_boxplot_grid

ggsave("figures/520_T_cell_CD8_diffusion/005_boxplots_mutsig.pdf", width = 5, height = 4.5)
ggsave("figures/520_T_cell_CD8_diffusion/005_boxplots_mutsig.png", width = 5, height = 4.5)

```

## patient violins

```{r chunk_520_180, fig.width=7, fig.height=8}


patient_violin_wrapper <- function(koi, ylabel = "Module score") {

  mutsig_boxplot_data_ranked <- filter(mutsig_boxplot_data_full, key == koi) %>%
    group_by(patient_id_short) %>% 
    mutate(median = median(value)) %>%
    ungroup %>% 
    arrange(median) %>% 
    mutate(patient_id_short = ordered(patient_id_short, levels = unique(patient_id_short)))
  
  ggplot(mutsig_boxplot_data_ranked) +
    geom_violin(aes(patient_id_short, value, fill = consensus_signature), 
                color = "white", adjust = 2, alpha = 0.5, width = 1.5) +
    geom_boxplot(aes(patient_id_short, value, color = consensus_signature),
                 width = 0.5, size = 0.75, outlier.shape = NA) +
    geom_boxplot(aes(patient_id_short, value, fill = consensus_signature),
                 color = "white", width = 0.5, outlier.shape = NA, size = 0.5) +
    facet_wrap(~key) +
    scale_color_manual(values = clrs$consensus_signature) +
    scale_fill_manual(values = clrs$consensus_signature) +
    theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)) +
    labs(x = "Patient", y = ylabel,
         fill = "Mutational\nsignature",
         color = "Mutational\nsignature") +
    remove_guides
  
}

patient_plots_list <- lapply(c("CD8\nNaive", "CD8\nDysfunct."), 
                             patient_violin_wrapper, "Module score") %>% 
  lapply(add, ylim(c(-1, 2)))

patient_plots_list[[3]] <- patient_violin_wrapper("JAK/STAT\npathway", "PROGENy score") +
  ylim(c(-1, 5))

plot_grid(plotlist = patient_plots_list, ncol = 1, align = "v")

ggsave("figures/520_T_cell_CD8_diffusion/005_violins_patient_lvl.pdf", 
            width = 8, height = 8)
ggsave("figures/520_T_cell_CD8_diffusion/005_violins_patient_lvl.png", 
       width = 8, height = 8)

```

```{r chunk_520_190, fig.width=22, fig.height=4}
  
ggdraw() +
  draw_plot(add_umap_coord(dc_plot_cluster + guides(color = F)), 
            x = 0.01, y = 0, width = 0.1, height = 0.5) +
  draw_plot(cowplot::get_legend(dc_plot_cluster), x = 0.01, y = 0.21) +
  draw_plot(dc_plot_genes, 
            x = 0.12, y = 0, width = 0.22, height = 1) +
  draw_plot(module_curves_module, x = 0.36, y = 0, width = 0.25, height = 1) +
  draw_plot(mutsig_boxplot_grid, 
            x = 0.65, y = 0, width = 0.35, height = 1)
  # draw_plot(dc_curve_cxcl13_full + guides(color = F), 
  #           x = 0.175, y = 0, width = 0.175, height = 0.5) +
  # draw_plot(cowplot::get_legend(dc_curve_isg_full), 
  #           x = 0.35, y = 0.45, width = 0.175, height = 0.2) +
  # draw_plot(dc_plot_isg + guides(color = F), x = 0.35, y = 0.7, width = 0.125, height = 0.3) +
  # draw_plot(dc_plot_cxcl13 + guides(color = F), x = 0.35, y = 0.05, width = 0.125, height = 0.3) +
  # draw_plot(box_grid, x = 0.5, y = 0, width = 0.5, height = 1)
  
ggsave("figures/520_T_cell_CD8_diffusion/004_CD8.T.cell.pdf", width = 22, height = 4)
ggsave("figures/520_T_cell_CD8_diffusion/004_CD8.T.cell.png", width = 22, height = 4)


```

```{r chunk_520_195, fig.width=3, fig.height=2.5}

dc_plot_dpt
ggsave("figures/520_T_cell_CD8_diffusion/004_CD8.T.cell_DC_pseudotime.pdf", width = 3, height = 2.5)
ggsave("figures/520_T_cell_CD8_diffusion/004_CD8.T.cell_DC_pseudotime.png", width = 3, height = 2.5)

```

## patient boxplots

```{r chunk_520_200, fig.width=24, fig.height=6}

koi <- "JAK/STAT\npathway"

patient_boxplot_wrapper <- function(koi, ylabel = "PROGENy score") {

  plot_data_pw_ranked_patients <- filter(mutsig_boxplot_data_full, key == koi) %>%
    # filter(patient_id_short %in% c("065", "054")) %>%
    group_by(patient_id_short) %>% 
    mutate(median = median(value)) %>%
    ungroup %>% 
    arrange(median) %>% 
    mutate(patient_id_short = ordered(patient_id_short, levels = unique(patient_id_short)))
  
  plot_data_pw_ranked_samples <- filter(mutsig_boxplot_data_full, key == koi) %>%
    # filter(patient_id_short %in% c("065", "054")) %>%
    group_by(sample) %>% 
    mutate(median = median(value),
           n = n()) %>%
    filter(n > 10) %>% 
    ungroup %>% 
    arrange(median) %>% 
    mutate(sample = ordered(sample, levels = unique(sample))) %>% 
    mutate(patient_id_short = ordered(patient_id_short, levels = levels(plot_data_pw_ranked_patients$patient_id_short)))
  
  plot_data_tumor_supersite_labels <- plot_data_pw_ranked_samples %>% 
    distinct(sample, .keep_all = T)
  
  upper_ylim <- filter(mutsig_boxplot_data_full, key == koi) %>% 
    # filter(patient_id_short %in% c("065", "054")) %>%
    group_by(sample) %>% 
    mutate(upper_whisker = 1.5*(quantile(value, 0.75) - quantile(value, 0.25))+quantile(value, 0.75)) %>% 
    pull(upper_whisker) %>% 
    unique %>% 
    max
  
  ggplot(plot_data_pw_ranked_samples) +
    geom_boxplot(aes(sample, value), fill = NA, 
                 width = 0.1, outlier.shape = NA, size = 0.5) +
    geom_boxplot(aes(sample, value, fill = consensus_signature), coef = 0,
                 outlier.shape = NA, size = 0.5, color = NA) +
    geom_point(aes(sample, median), color = "white", size = 0.35,
               data = plot_data_tumor_supersite_labels) +
    geom_point(aes(sample, color = tumor_supersite), 
               y = -1, size = 1, shape = 15,
               data = plot_data_tumor_supersite_labels) +
    geom_hline(aes(yintercept = median), alpha = 0.65,
               data = distinct(plot_data_pw_ranked_patients, 
                               patient_id_short, .keep_all = T)) +
    facet_grid(~patient_id_short, scales = "free_x", space = "free_x", 
               switch = "x") +
    scale_color_manual(values = clrs$tumor_supersite) +
    scale_fill_manual(values = clrs$consensus_signature[c(mois, "Undetermined")]) +
    theme(axis.text.x = element_blank(),
          strip.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
          axis.ticks.x = element_blank(),
          axis.line.x = element_blank(),
          plot.title = element_text(vjust = 0.5, hjust = 0.5, face = "plain"),
          panel.spacing = unit(2, "points")) +
    coord_cartesian(clip = "off") + 
    scale_y_continuous(limits = c(-2, upper_ylim), breaks = seq(-3, 9, by = 3)) +
    labs(x = "Patient", y = ylabel,
         fill = "Mutational\nsignature",
         color = "Mutational\nsignature",
         title = str_replace_all(koi, "\n", " "))

}

```

```{r chunk_520_210, fig.width=10, fig.height=8}

patient_boxplots_list <- lapply(c("CD8\nNaive", "CD8\nDysfunct."), 
                             patient_boxplot_wrapper, "Module score") %>% 
  lapply(add, ylim(c(-1, 2)))

patient_boxplots_list[[3]] <- patient_boxplot_wrapper("JAK/STAT\npathway", "PROGENy score") +
  ylim(c(-1, 6))

box_grid <- plot_grid(plotlist = patient_boxplots_list %>% lapply(add, remove_guides), ncol = 1)

ggdraw() + 
  draw_plot(box_grid, width = 0.8, height = 1) +
  draw_grob(get_legend(patient_boxplots_list[[1]]), x = 0.82, y = 0)

ggsave("figures/520_T_cell_CD8_diffusion/005_boxplots_patient_lvl.pdf", 
            width = 10, height = 8)
ggsave("figures/520_T_cell_CD8_diffusion/005_boxplots_patient_lvl.png", 
       width = 10, height = 8)


```

## correlation

```{r chunk_520_230, fig.width=8, fig.height=3}

plot_data_cc <- as_tibble(FetchData(seu_obj_cc, c("sample", "JAK.STAT.pathway", "CD274"))) %>% 
  gather(key_cc, value, -sample) %>% 
  left_join(scrna_meta_tbl, by = "sample") %>% 
  filter(sort_short == "CD45-") %>% 
  group_by(sample, key_cc, patient_id_short, tumor_supersite, consensus_signature) %>% 
  summarise(mean_value_cc = mean(value)) %>% 
  ungroup %>% 
  mutate(sample = str_remove_all(sample, "_CD45N|_CD45P"))

plot_data_cor <- as_tibble(FetchData(seu_obj_cd8_sub, c("sample", "JAK.STAT.pathway", "CD8.Dysfunctional.module"))) %>% 
  gather(key_tc, value, -sample) %>% 
  left_join(scrna_meta_tbl, by = "sample") %>% 
  filter(sort_short == "CD45+") %>% 
  group_by(sample, key_tc) %>% 
  summarise(mean_value_tc = mean(value)) %>% 
  ungroup %>% 
  mutate(sample = str_remove_all(sample, "_CD45N|_CD45P")) %>% 
  inner_join(plot_data_cc, by = "sample") %>% 
  filter(!(consensus_signature %in% c("Undetermined", "HRD")))

cor_plot1 <- plot_data_cor %>% 
  filter(key_tc == "CD8.Dysfunctional.module", key_cc == "CD274") %>% 
  ggplot() +
  geom_point(aes(mean_value_cc, mean_value_tc, color = consensus_signature)) +
  geom_smooth(aes(mean_value_cc, mean_value_tc), method = "lm", se = T,
              linetype = 2, size = 0.5, color = "black") +
  stat_cor(aes(mean_value_cc, mean_value_tc), 
           method = "spearman", color = "black") +
  scale_color_manual(values = clrs$consensus_signature[mois]) +
  labs(y = "Dysfunctional score\n(CD8+ T cells)", 
       x = "CD274 expression\n(cancer cells)",
       color = "Mutational\nsignature")

cor_plot2 <- {cor_plot1 + 
    labs(y = "JAK-STAT score\n(CD8+ T cells)", 
         x = "JAK-STAT score\n(cancer cells)",
         color = "Mutational\nsignature")
} %+%
  filter(plot_data_cor, key_tc == "JAK.STAT.pathway", 
         key_cc == "JAK.STAT.pathway")

cor_plot_grid <- plot_grid(cor_plot1 + guides(color = F), cor_plot2,
                           align = "hv", axis = "x", 
                           rel_widths = c(0.42, 0.58))

cor_plot_grid

ggsave("figures/520_T_cell_CD8_diffusion/004_tcell_cancer_cell_correlation.pdf", cor_plot_grid, width = 7.75, height = 3)
ggsave("figures/520_T_cell_CD8_diffusion/004_tcell_cancer_cell_correlation.png", cor_plot_grid, width = 7.75, height = 3)


```


## composition

### scRNA

```{r chunk_520_240, fig.width=24, fig.height=6}

source("src/comp_plot.R")

comp_tbl_cd8 <- distinct(plot_data, cell_id, .keep_all = T) %>% 
  # filter(tumor_supersite != "Ascites") %>% 
  mutate(sample_id = sample) %>% 
  filter(sort_short_x == "CD45+") %>% 
  group_by(sample_id, sort_short_x, consensus_signature, tumor_supersite, cluster_label_sub) %>% 
  tally %>% 
  group_by(sample_id, sort_short_x, consensus_signature, tumor_supersite) %>% 
  mutate(nrel = n/sum(n)*100) %>% 
  mutate(tumor_supersite = ordered(tumor_supersite, levels = rev(names(clrs$tumor_supersite))))

plist1 <- default_comp_grid_list(
  comp_tbl_cd8, cluster_label_sub, "CD8.T.naive.centr.mem.1", nmax = 2000,
  cluster_label_sub, super_type_sub = "T.super", vec_plot = F)

plist2 <- default_comp_grid_list(
  comp_tbl_cd8, cluster_label_sub, "CD8.T.naive.centr.mem.2", nmax = 2000,
  cluster_label_sub, super_type_sub = "T.super", vec_plot = F)

plist3 <- default_comp_grid_list(
  comp_tbl_cd8, cluster_label_sub, "CD8.T.effector.memory", nmax = 2000, 
  cluster_label_sub, super_type_sub = "T.super", vec_plot = F)

plist4 <- default_comp_grid_list(
  comp_tbl_cd8, cluster_label_sub, "CD8.T.cytotoxic", nmax = 2000, 
  cluster_label_sub, super_type_sub = "T.super", vec_plot = F)

plist5 <- default_comp_grid_list(
  comp_tbl_cd8, cluster_label_sub, "CD8.T.dysfunc.early", nmax = 2000, 
  cluster_label_sub, super_type_sub = "T.super", vec_plot = F)

plist6 <- default_comp_grid_list(
  comp_tbl_cd8, cluster_label_sub, "CD8.T.dysfunc.late", nmax = 2000, 
  cluster_label_sub, super_type_sub = "T.super", vec_plot = F)

plist7 <- default_comp_grid_list(
  comp_tbl_cd8, cluster_label_sub, "CD8.T.dysfunc.ISG", nmax = 2000, 
  cluster_label_sub, super_type_sub = "T.super", vec_plot = F)

plist8 <- default_comp_grid_list(
  comp_tbl_cd8, cluster_label_sub, "CD8.T.ISG.early", nmax = 2000, 
  cluster_label_sub, super_type_sub = "T.super", vec_plot = F)

plist9 <- default_comp_grid_list(
  comp_tbl_cd8, cluster_label_sub, "CD8.T.ISG.late", nmax = 2000, 
  cluster_label_sub, super_type_sub = "T.super", vec_plot = F)

comp_grid1 <- plot_grid(plotlist = plist1, ncol = 1, align = "v", rel_heights = c(0.2, 0.2, 0.25, 0.35))

comp_grid2 <- plot_grid(plotlist = plist2, ncol = 1, align = "v", rel_heights = c(0.2, 0.2, 0.25, 0.35))

comp_grid3 <- plot_grid(plotlist = plist3, ncol = 1, align = "v", rel_heights = c(0.2, 0.2, 0.25, 0.35))

comp_grid4 <- plot_grid(plotlist = plist4, ncol = 1, align = "v", rel_heights = c(0.2, 0.2, 0.25, 0.35))

comp_grid5 <- plot_grid(plotlist = plist5, ncol = 1, align = "v", rel_heights = c(0.2, 0.2, 0.25, 0.35))

comp_grid6 <- plot_grid(plotlist = plist6, ncol = 1, align = "v", rel_heights = c(0.2, 0.2, 0.25, 0.35))

comp_grid7 <- plot_grid(plotlist = plist7, ncol = 1, align = "v", rel_heights = c(0.2, 0.2, 0.25, 0.35))

comp_grid8 <- plot_grid(plotlist = plist8, ncol = 1, align = "v", rel_heights = c(0.2, 0.2, 0.25, 0.35))

comp_grid9 <- plot_grid(plotlist = plist9, ncol = 1, align = "v", rel_heights = c(0.2, 0.2, 0.25, 0.35))

pg <- plot_grid(comp_grid1, comp_grid2, comp_grid3, comp_grid4, comp_grid5, comp_grid6, comp_grid7, comp_grid8, comp_grid9, ncol = 9)
pg

ggsave("figures/520_T_cell_CD8_diffusion/004_CD8.T.cell_composition.pdf", pg, width = 27, height = 6)
ggsave("figures/520_T_cell_CD8_diffusion/004_CD8.T.cell_composition.png", pg, width = 27, height = 6)

```

## session info

```{r chunk_520_999}

# devtools::session_info()

```


