---
title: "MSK SPECTRUM freeze major subset deep dives"
author: "Florian Uhlitz"
date: "`r Sys.Date()`"
output:
  bookdown::html_document2:
    includes:
      in_header: header.html
  bookdown::gitbook:
    includes:
      in_header: header.html
editor_options: 
  chunk_output_type: console
---


# Figure 6 upper

```{r chunk_610_010}

library(magrittr)
library(tidyverse)
library(Seurat)
library(readxl)
library(cowplot)
library(colorblindr)
library(viridis)
library(ComplexHeatmap)
library(grid)

coi <- "Myeloid.super"
cell_sort <- "CD45+"
cell_type_major <- c("Myeloid.cell", "Dendritic.cell", "Mast.cell")
louvain_resolution <- 0.3
louvain_cluster <- "RNA_snn_res.0.3"
pcut <- 0.05

# p1 <- ggplot(data.frame(x = 1:5, y = 1:5), aes(x, y)) + geom_point()
# vp_outer <- viewport(x = 0.5, y = 0.5, width = 0.5, height = 0.5, angle = 90)
# vp_inner <- viewport(x = 0.5, y = 0.5, width = 1, height = 1, angle = 0)
# grid.newpage()
# pushViewport(vp_outer)
# grid.rect()
# print(p1, vp = vp_inner)
# popViewport(1)
# g1 <- grid.grab()
# ggdraw() + draw_grob(g1)


```

```{r chunk_610_020}

## load global vars: 
source("src/global_vars.R")

# scrna_meta_tbl
# clrs
# markers_v7
# markers_v7_super
# cell_type_super_lookup

```

```{r chunk_610_030}

myfeatures <- c("UMAP_1", "UMAP_2", "umapharmony_1", "umapharmony_2", "sample", "doublet", "nCount_RNA", "nFeature_RNA", "percent.mt", "doublet_score", "cell_type", "cluster_label")

seu_obj_sub <- read_rds(paste0("/work/shah/users/uhlitzf/data/SPECTRUM/freeze/v7/", coi, "_processed_filtered_annotated.rds"))

seu_obj_sub_mp <- read_rds(paste0("/work/shah/users/uhlitzf/data/SPECTRUM/freeze/v7/Macrophages_processed.rds"))

seu_obj_sub_dc <- read_rds(paste0("/work/shah/users/uhlitzf/data/SPECTRUM/freeze/v7/DCs_processed.rds"))

marker_tbl <- read_tsv(paste0("/work/shah/users/uhlitzf/data/SPECTRUM/freeze/v7/supplementary_tables/", coi, "_marker_table_annotated.tsv"))

marker_tbl_top <- marker_tbl %>% 
  filter(avg_logFC > 0.5,
         p_val_adj < 0.01,
         pct.1 > 0.2,
         pct.2 < 0.8,
         !is.na(cluster_label),
         !str_detect(gene, "^RPS|^RPL")) %>% 
  group_by(cluster_label) %>% 
  slice(1:50)

marker_sheet <- read_tsv(paste0("/work/shah/users/uhlitzf/data/SPECTRUM/freeze/v7/supplementary_tables/", coi, "_marker_sheet.tsv"))

my_subtypes <- names(clrs$cluster_label[[coi]])

plot_data_sub <- list(Macrophage = FetchData(seu_obj_sub_mp, c(myfeatures)),
                      DC = FetchData(seu_obj_sub_dc, c(myfeatures))) %>% 
  bind_rows(.id = "cell_type_myeloid") %>% 
  as_tibble() %>% 
  left_join(scrna_meta_tbl, by = "sample") %>% 
  mutate(cell_type_super = cell_type_super_lookup[cell_type]) %>% 
  mutate(sort_short = str_remove_all(sort_parameters, "singlet, live, ")) %>% 
  mutate(sort_short_x = ifelse(sort_short == "U" & cell_type_super == "Immune", 
                               "CD45+", ifelse(sort_short == "U" & cell_type_super == "Stromal", "CD45-", sort_short)),
         cluster_label = ordered(cluster_label, levels = names(clrs$cluster_label[[coi]])))
  
plot_data_sub <- filter(plot_data_sub, sort_short_x == cell_sort, !is.na(tumor_supersite))

```

## UMAP

```{r chunk_610_50, fig.width=7, fig.height=4}

alpha_lvl <- ifelse(nrow(plot_data_sub) < 20000, 0.2, 0.1)
pt_size <- ifelse(nrow(plot_data_sub) < 20000, 0.2, 0.05)

common_layers_disc <- list(  
  ggrastr::geom_point_rast(size = pt_size, alpha = alpha_lvl, raster.dpi = 150),
  NoAxes(),
  guides(color = guide_legend(override.aes = list(size = 2, alpha = 1))),
  labs(color = ""),
  theme(aspect.ratio = 1)
)

common_layers_cont <- list(  
  ggrastr::geom_point_rast(size = pt_size, alpha = alpha_lvl, raster.dpi = 150),
  NoAxes(),
  scale_color_gradientn(colors = viridis(9)),
  guides(color = guide_colorbar())
)

umap_coord_anno <- function(size) {
  ggplot(tibble(group = c("UMAP1", "UMAP2"),
                x = c(0, 0), xend = c(1, 0),
                y = c(0, 0), yend = c(0, 1),
                lx = c(0.5, -0.15), ly = c(-0.15, 0.5),
                angle = c(0, 90))) +
    geom_segment(aes(x, y, xend = xend, yend = yend, group = group),
                 arrow = arrow(angle = 20, type = "closed", length = unit(0.1, "npc")),
                 size = size/4, lineend = "round") +
    geom_text(aes(lx, ly, label = group, angle = angle), size = size) +
    theme_void() +
    coord_fixed(xlim = c(-0.3, 1), ylim = c(-0.3, 1))
}

add_umap_coord <- function(gg_obj, x = 0, y = 0, width = 0.3, height = 0.3, size = 4.5) {
  p <- ggdraw() + 
    draw_plot(gg_obj, x = 0, y = 0, width = 1, height = 1) +
    draw_plot(umap_coord_anno(size = size), x = x, y = y, width = width, height = height)
  return(p)
}

```

```{r chunk_610_60, fig.width=7, fig.height=4}

plot_data_label <- plot_data_sub %>% 
  group_by(cluster_label, cell_type_myeloid) %>% 
  summarise(umapharmony_1 = median(umapharmony_1),
            umapharmony_2 = median(umapharmony_2)) %>% 
  mutate(cluster_number = as.numeric(cluster_label))

umap_cell_type <- ggplot(plot_data_sub, aes(umapharmony_1, umapharmony_2, color = cluster_label)) + 
  common_layers_disc +
  facet_wrap(~cell_type_myeloid, scales = "free") +
  # geom_label(aes(umapharmony_1, umapharmony_2, label = cluster_label), color = "black",
  #            data = plot_data_label, label.size = unit(0, "mm"), label.r = unit(0, "mm"),
  #            alpha = 0.5, nudge_y = 1, nudge_x = -1) +
  geom_point(aes(umapharmony_1, umapharmony_2), color = "white",
             data = plot_data_label, alpha = 0.5, size = 6) +
  geom_text(aes(umapharmony_1, umapharmony_2, label = cluster_number), color = "black",
             data = plot_data_label) +
  scale_color_manual(values = clrs$cluster_label[[coi]]) +
  guides(color = guide_legend(override.aes = list(size = 2, alpha = 1)))

umap_site <- ggplot(plot_data_sub, aes(umapharmony_1, umapharmony_2, color = tumor_supersite)) + 
  common_layers_disc +
  facet_wrap(~cell_type_myeloid, scales = "free") +
  scale_color_manual(values = clrs$tumor_supersite)

umap_cell_type_void <- umap_cell_type + guides(color = F)
umap_site_void <- umap_site + guides(color = F)

umap_cell_type_legend <- cowplot::get_legend(umap_cell_type)
umap_site_legend <- cowplot::get_legend(umap_site)

```

## marker heatmap 

```{r chunk_610_70, fig.width=15, fig.height=5}

plot_data_markers <- as_tibble(FetchData(seu_obj_sub, c(myfeatures, unique(marker_tbl_top$gene)))) %>% 
  gather(gene, value, -c(1:(length(myfeatures)+1))) %>% 
  left_join(scrna_meta_tbl, by = "sample") %>% 
  mutate(cluster_label = ordered(cluster_label, levels = my_subtypes)) %>% 
  group_by(cluster_label, gene) %>% 
  summarise(value = mean(value, na.rm = T)) %>% 
  group_by(gene) %>% 
  mutate(value = scales::rescale(value)) %>% 
  left_join(select(marker_tbl_top, cluster_label_x = cluster_label, gene), by = "gene") %>% 
  mutate(cluster_label_x = ordered(cluster_label_x, levels = rev(names(clrs$cluster_label[[coi]])))) %>% 
  na.omit()

```

```{r chunk_610_75, fig.width=15, fig.height=5}

highlight_genes <- marker_tbl_top %>% 
  group_by(cluster_label) %>% 
  slice(1:2) %>% 
  mutate(cluster_label_x = ordered(cluster_label, levels = rev(names(clrs$cluster_label[[coi]])))) %>% 
  ungroup() %>% 
  select(cluster_label_x, gene) %>% 
  na.omit %>% 
  mutate(highlight = T)

plot_data_markers_mat <- plot_data_markers %>% 
  spread(cluster_label, value) %>% 
  left_join(highlight_genes, by = c("gene", "cluster_label_x")) %>% 
  arrange(desc(cluster_label_x), gene) %>% 
  select(cluster_label_x, gene, highlight, everything())

ha_row <- rowAnnotation(
  `Cell type` = plot_data_markers_mat$cluster_label_x,
  col = list(`Cell type` = clrs$cluster_label[[coi]]),
  show_legend = F,
  annotation_name_side = "bottom"
)

ha_col <- columnAnnotation(
  `Cell type` = anno_block(gp = gpar(fill = clrs$cluster_label[[coi]], col = NA),
                           labels = as.character(1:(ncol(plot_data_markers_mat)-3)),
                           labels_rot = 90),
  show_legend = F,
  annotation_name_side = "left",
  annotation_name_rot = 0
)

gene_idx <- plot_data_markers_mat$highlight == TRUE

ha_genes <- rowAnnotation(
  link = anno_mark(
    at = which(gene_idx),
    labels = plot_data_markers_mat$gene[which(gene_idx)],
    labels_gp = gpar(fontsize = 10), padding = unit(1, "mm"),
    side = "left",
    labels_rot = 180
  )
)

marker_heatmap <- Heatmap(
  as.matrix(plot_data_markers_mat[,-c(1:3)]), 
  heatmap_legend_param = list(
    title = "Scaled expression", 
    title_position = "leftcenter-rot"
  ),
  row_order = 1:length(plot_data_markers_mat$cluster_label_x),
  row_split = plot_data_markers_mat$cluster_label_x, 
  column_split = 1:length(colnames(plot_data_markers_mat)[-c(1:3)]),
  column_order = colnames(plot_data_markers_mat)[-c(1:3)], 
  column_names_side = "bottom",
  right_annotation = ha_row,
  left_annotation = ha_genes,
  bottom_annotation = ha_col,
  cluster_rows = F, 
  row_title = NULL,
  column_title = NULL,
  col = viridis(9)
)

# marker_heatmap

```

## composition

### per site

```{r chunk_610_080, fig.width=3, fig.height=10}

source("src/comp_plot.R")

comp_tbl_sample_sort <- plot_data_sub %>%
  mutate(cell_type_super_ml = ifelse(cluster_label %in% grep("DC", names(clrs$cluster_label[[coi]]), value = T), "Dendritic cell", "Macrophage")) %>% 
  filter(therapy == "pre-Rx") %>%
  group_by(sample, tumor_subsite, tumor_supersite, tumor_megasite, patient_id_short,
           therapy, sort_short_x, consensus_signature, cluster_label, cell_type_super_ml) %>%
  tally() %>%
  ungroup() %>%
  # Pad cell type combinations with zero counts in the data
  complete(cluster_label,
           nesting(sample, tumor_subsite, tumor_supersite, tumor_megasite,
                   patient_id_short, therapy, sort_short_x, consensus_signature),
           fill = list(n = 0)) %>%
  group_by(sample, tumor_subsite, tumor_supersite, tumor_megasite, patient_id_short,
           therapy, sort_short_x, consensus_signature) %>%
  mutate(nrel = n/sum(n)*100,
         log10n = log10(n)) %>%
  mutate(sample_id = sample) %>%
  mutate(tumor_supersite = ordered(tumor_supersite, levels = rev(names(clrs$tumor_supersite))))

comp_tbl_sample_sort_mp <- plot_data_sub %>%
  mutate(cell_type_super_ml = ifelse(cluster_label %in% grep("DC", names(clrs$cluster_label[[coi]]), value = T), "Dendritic cell", "Macrophage")) %>% 
  filter(therapy == "pre-Rx", cell_type_super_ml == "Macrophage", str_detect(cluster_label, "M[1-2]\\.|Cycling.M|Clearing.M")) %>%
  group_by(sample, tumor_subsite, tumor_supersite, tumor_megasite, patient_id_short,
           therapy, sort_short_x, consensus_signature, cluster_label, cell_type_super_ml) %>%
  tally() %>%
  ungroup() %>%
  # Pad cell type combinations with zero counts in the data
  complete(cluster_label,
           nesting(sample, tumor_subsite, tumor_supersite, tumor_megasite,
                   patient_id_short, therapy, sort_short_x, consensus_signature),
           fill = list(n = 0)) %>%
  group_by(sample, tumor_subsite, tumor_supersite, tumor_megasite, patient_id_short,
           therapy, sort_short_x, consensus_signature) %>%
  mutate(nrel = n/sum(n)*100,
         log10n = log10(n)) %>%
  mutate(sample_id = sample) %>%
  mutate(tumor_supersite = ordered(tumor_supersite, levels = rev(names(clrs$tumor_supersite))))

plist1 <- default_comp_grid_list(
  comp_tbl_sample_sort_mp, cluster_label, "M1.S100A8",
  cluster_label, super_type = "Myeloid.super", nmax = 5000, highlight = T)

plist2 <- default_comp_grid_list(
  comp_tbl_sample_sort_mp, cluster_label, "M2.CXCL10",
  cluster_label, super_type = "Myeloid.super", nmax = 5000, highlight = T)

plist3 <- default_comp_grid_list(
  comp_tbl_sample_sort_mp, cluster_label, "M2.SELENOP",
  cluster_label, super_type = "Myeloid.super", nmax = 5000, highlight = T)

plist4 <- default_comp_grid_list(
  comp_tbl_sample_sort_mp, cluster_label, "M2.MARCO",
  cluster_label, super_type = "Myeloid.super", nmax = 5000, highlight = T)

plist5 <- default_comp_grid_list(
  comp_tbl_sample_sort_mp, cluster_label, "M2.COL1A1",
  cluster_label, super_type = "Myeloid.super", nmax = 5000, highlight = T)

plist6 <- default_comp_grid_list(
  comp_tbl_sample_sort_mp, cluster_label, "M2.MMP9",
  cluster_label, super_type = "Myeloid.super", nmax = 5000, highlight = T)

plist7 <- default_comp_grid_list(
  comp_tbl_sample_sort, cell_type_super_ml, "Dendritic cell",
  cluster_label, super_type = "Myeloid.super", nmax = 5000, highlight = T)

plist8 <- default_comp_grid_list(
  filter(comp_tbl_sample_sort, tumor_supersite != "Ascites"), 
  cell_type_super_ml, "Dendritic cell",
  cluster_label, super_type = "Myeloid.super", nmax = 5000, highlight = T)

comp_grid1 <- plot_grid(plotlist = plist1[-3], ncol = 1, align = "v", rel_heights = c(0.15, 0.15, 0.2, 0.5))

comp_grid2 <- plot_grid(plotlist = plist2[-3], ncol = 1, align = "v", rel_heights = c(0.15, 0.15, 0.2, 0.5))

comp_grid3 <- plot_grid(plotlist = plist3[-3], ncol = 1, align = "v", rel_heights = c(0.15, 0.15, 0.2, 0.5))

comp_grid4 <- plot_grid(plotlist = plist4[-3], ncol = 1, align = "v", rel_heights = c(0.15, 0.15, 0.2, 0.5))

comp_grid5 <- plot_grid(plotlist = plist5[-3], ncol = 1, align = "v", rel_heights = c(0.15, 0.15, 0.2, 0.5))

comp_grid6 <- plot_grid(plotlist = plist6[-3], ncol = 1, align = "v", rel_heights = c(0.15, 0.15, 0.2, 0.5))

comp_grid7 <- plot_grid(plotlist = plist7[-3], ncol = 1, align = "v", rel_heights = c(0.15, 0.15, 0.2, 0.5))

comp_grid8 <- plot_grid(plotlist = plist8[-3], ncol = 1, align = "v", rel_heights = c(0.15, 0.15, 0.2, 0.5))

```

```{r chunk_610_090, fig.width=3, fig.height=9}

comp_grid1
ggsave_pdf("figures/610_Myeloid_cell_plotting_umap_comp_heatmap/005_Macrophage.cell_comp_1.pdf", comp_grid1, width = 3, height = 9)
ggsave_png("figures/610_Myeloid_cell_plotting_umap_comp_heatmap/005_Macrophage.cell_comp_1.png", comp_grid1, width = 3, height = 9)

comp_grid2
ggsave_pdf("figures/610_Myeloid_cell_plotting_umap_comp_heatmap/005_Macrophage.cell_comp_2.pdf", comp_grid2, width = 3, height = 9)
ggsave_png("figures/610_Myeloid_cell_plotting_umap_comp_heatmap/005_Macrophage.cell_comp_2.png", comp_grid2, width = 3, height = 9)

comp_grid3
ggsave_pdf("figures/610_Myeloid_cell_plotting_umap_comp_heatmap/005_Macrophage.cell_comp_3.pdf", comp_grid3, width = 3, height = 9)
ggsave_png("figures/610_Myeloid_cell_plotting_umap_comp_heatmap/005_Macrophage.cell_comp_3.png", comp_grid3, width = 3, height = 9)

comp_grid4
ggsave_pdf("figures/610_Myeloid_cell_plotting_umap_comp_heatmap/005_Macrophage.cell_comp_4.pdf", comp_grid4, width = 3, height = 9)
ggsave_png("figures/610_Myeloid_cell_plotting_umap_comp_heatmap/005_Macrophage.cell_comp_4.png", comp_grid4, width = 3, height = 9)

comp_grid5
ggsave_pdf("figures/610_Myeloid_cell_plotting_umap_comp_heatmap/005_Macrophage.cell_comp_5.pdf", comp_grid5, width = 3, height = 9)
ggsave_png("figures/610_Myeloid_cell_plotting_umap_comp_heatmap/005_Macrophage.cell_comp_5.png", comp_grid5, width = 3, height = 9)

comp_grid6
ggsave_pdf("figures/610_Myeloid_cell_plotting_umap_comp_heatmap/005_Macrophage.cell_comp_6.pdf", comp_grid5, width = 3, height = 9)
ggsave_png("figures/610_Myeloid_cell_plotting_umap_comp_heatmap/005_Macrophage.cell_comp_6.png", comp_grid5, width = 3, height = 9)

```

```{r chunk_610_100, fig.width=3, fig.height=9}

comp_grid7
ggsave_pdf("figures/610_Myeloid_cell_plotting_umap_comp_heatmap/005_Myeloid.cell_comp.pdf", comp_grid7, width = 3, height = 9)
ggsave_png("figures/610_Myeloid_cell_plotting_umap_comp_heatmap/005_Myeloid.cell_comp.png", comp_grid7, width = 3, height = 9)

comp_grid8
ggsave_pdf("figures/610_Myeloid_cell_plotting_umap_comp_heatmap/005_Myeloid.cell_comp_no_ascites.pdf", comp_grid8, width = 3, height = 9)
ggsave_png("figures/610_Myeloid_cell_plotting_umap_comp_heatmap/005_Myeloid.cell_comp_no_ascites.png", comp_grid8, width = 3, height = 9)

```

```{r chunk_610_110, fig.width=16, fig.height=4}

heatmap_grob <- grid.grabExpr(draw(marker_heatmap), width = 4, height = 8)
vp_outer <- viewport(x = 0.5, y = 0.5, width = 0.5, height = 2, angle = 270)
vp_inner <- viewport(x = 0.5, y = 0.5, width = 1, height = 1, angle = 0)
grid.newpage()
pushViewport(vp_outer)
grid.draw(heatmap_grob)
popViewport(1)
heatmap_grob_rot <- grid.grab()

umap_heat_grid <- ggdraw() +
  draw_plot(add_umap_coord(umap_cell_type_void, size = 4.5, x = 0),
            x = 0, y = 0, width = 0.5, height = 1) +
  # draw_plot(add_umap_coord(umap_site_void, size = 3.5, x = 0),
  #           x = 0, y = 0, width = 0.2, height = 0.5) +
  draw_grob(heatmap_grob_rot,
            x = 0.5, y = 0, width = 0.5, height = 1)
  # draw_plot_label(c("A", "B", "C", "D"), x = c(0, 0.63, 0, 0), y = c(0.995, 0.995, 0.72, 0.45))

umap_heat_grid

ggsave_png("figures/610_Myeloid_cell_plotting_umap_comp_heatmap/005_Myeloid.cell_umap_heat.png", umap_heat_grid, width = 16, height = 4)
ggsave_pdf("figures/610_Myeloid_cell_plotting_umap_comp_heatmap/005_Myeloid.cell_umap_heat.pdf", umap_heat_grid, width = 16, height = 4)

```


## session info

```{r chunk_610_999}

devtools::session_info()

```


