---
title: "Generalized linear model of myeloid cell composition"
subtitle: "MSK SPECTRUM"
author:
  - "Ignacio Vazquez-Garcia"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    highlight: tango
    df_print: paged
    code_folding: hide
    fig_align: center
    toc: true
    toc_float: true
    toc_depth: 3
    number_sections: yes
params:
   rmd: "630_Myeloid_cell_glm.Rmd"
---

# Generalized linear model of myeloid cell clusters

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r}
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(ggridges)
library(scales)
library(data.table)
library(tidytext)
library(cowplot)
library(ggthemes)
library(ggrepel)
library(corrplot)
library(viridisLite)
library(grid)
library(RColorBrewer)
library(lme4)
library(emmeans)
```

```{r}

## load global vars: 
source("src/global_vars.R")

names(clrs$patient_id) <- str_remove_all(names(clrs$patient_id), "SPECTRUM-OV-")
names(clrs$cell_type) <- str_replace_all(names(clrs$cell_type), "\\.", " ")

```

```{r}

# scRNA

# Cohort object
scrna_cohort_cell_tbl <-
  readr::read_tsv(
    "/work/shah/vazquezi/projects/spectrum/results/scrna/v27/download-data/outputs/cohort_metadata/SPECTRUM.tsv"
  )

# Cell supertype objects
scrna_myeloid_cell_tbl <-
  readr::read_tsv(
    "/work/shah/vazquezi/projects/spectrum/results/scrna/v27/download-data/outputs/cell_supertype_metadata/Myeloid.tsv"
  )

scrna_cell_tbl <- scrna_cohort_cell_tbl %>%
  dplyr::left_join(scrna_myeloid_cell_tbl %>% dplyr::select(cell_id, cluster_label),
                   by = 'cell_id') %>%
  dplyr::left_join(db$mutational_signatures, by = 'patient_id') %>%
  dplyr::filter(tumor_supersite != "Unknown") %>%
  dplyr::mutate(
    patient_id = str_remove(patient_id, "SPECTRUM-OV-"),
    sample_id = str_remove(sample_id, "OV-")
  )

scrna_cell_tbl <- scrna_cell_tbl %>% mutate(
  consensus_signature = ordered(consensus_signature, levels = names(clrs$consensus_signature)),
  consensus_signature_short = ordered(
    consensus_signature_short,
    levels = names(clrs$consensus_signature_short)
  ),
  tumor_type = ordered(tumor_type, levels = names(clrs$tumor_type)),
  tumor_supersite = ordered(tumor_supersite, levels = names(clrs$tumor_supersite)),
  therapy = ordered(therapy, levels = names(clrs$therapy)),
  cell_type = ordered(cell_type, levels = names(clrs$cell_type))
)

```

```{r}

heatmap_layers <- list(
  scale_fill_gradient2(low = scales::muted("blue"), high = scales::muted("red"), 
                       na.value = "grey10"),
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
        axis.ticks = element_blank(),
        axis.line = element_blank(),
        axis.title = element_blank(),
        plot.margin = margin(0, 0, 0, 0),
        strip.text = element_blank())
)

```

```{r}

data <- list()
formulas <- list()
models <- list()
consensus_signature_emm <- list()
site_emm <- list()

```

## Myeloid cell super clusters {.tabset}

```{r}

scrna_cluster_super_sample_tbl <- scrna_cell_tbl %>%
  mutate(cluster_label_super = case_when(
        str_detect(cluster_label, "M1") ~ "M1",
        str_detect(cluster_label, "M2") ~ "M2",
        str_detect(cluster_label, "DC") ~ "DC",
        TRUE ~ "Other"
        )) %>%
  mutate(cell_type = as.character(cell_type)) %>%
  mutate(cluster_label_super = ordered(cluster_label_super, levels = c("M1", "M2", "DC", "Other"))) %>%
  group_by(patient_id, consensus_signature, consensus_signature_short, tumor_type, tumor_supersite, tumor_subsite, therapy, sort_parameters, cell_type, cluster_label_super) %>%
  summarize(cell_state_count = n_distinct(cell_id)) %>% 
  mutate(
      other_cell_state_count = sum(cell_state_count) - cell_state_count,
      total_cell_state_count = sum(cell_state_count),
      cell_state_proportion = cell_state_count/total_cell_state_count*100
      ) %>%
  ungroup

```

```{r}

data[["Myeloid cell"]] <- scrna_cluster_super_sample_tbl %>%
  filter(str_detect(sort_parameters, "U|CD45+")) %>%
  filter(str_detect(cell_type, "Monocyte"))
formulas[["Myeloid cell"]] <-cbind(cell_state_count, other_cell_state_count) ~ cluster_label_super * consensus_signature + cluster_label_super * tumor_supersite #+ cluster_label_super * sort_parameters
models[["Myeloid cell"]] <- glm(formula = formulas[["Myeloid cell"]], family = binomial(link = 'logit'), data = data[["Myeloid cell"]])

consensus_signature_emm[["Myeloid cell"]] <- emmeans(models[["Myeloid cell"]], specs = eff ~ consensus_signature | cluster_label_super, type = "response", tran = "logit", adjust = "bonferroni")
consensus_signature_odds <- consensus_signature_emm[["Myeloid cell"]]$contrasts %>%
  rbind() %>%
  as.data.frame()

site_emm[["Myeloid cell"]] <- emmeans(models[["Myeloid cell"]], specs = eff ~ tumor_supersite | cluster_label_super, type = "response", tran = "logit", adjust = "bonferroni")
site_odds <- site_emm[["Myeloid cell"]]$contrasts %>%
  rbind() %>%
  as.data.frame()

```

```{r, fig.width = 3.6, fig.height = 4.5, results = "asis"}

plot_data <- bind_rows(consensus_signature_odds %>% add_column(contrast_variable = "Signature"),
                       site_odds %>% add_column(contrast_variable = "Site")) %>%
  # filter(p.value < 1E-20) %>%
  # filter(SE < 0.05) %>%
  mutate(p.value = ifelse(p.value < 1E-250, 1E-250, p.value)) %>%
  filter(!str_detect(contrast, "HRD effect")) %>%
  mutate(contrast = str_remove(contrast, " effect")) %>%
  mutate(contrast = str_remove(contrast, "\\(")) %>%
  mutate(contrast = str_remove(contrast, "\\)")) %>%
  mutate(contrast = ordered(contrast, levels = c(names(clrs$consensus_signature), names(clrs$tumor_supersite)))) %>%
  mutate(cluster_label_super = ordered(cluster_label_super, levels = c("M1", "M2", "DC", "Other"))) %>%
  filter(!str_detect(contrast, "Undetermined")) %>%
  filter(!str_detect(contrast, "Other")) %>%
  mutate(log2.odds.ratio = log2(odds.ratio)) %>%
  mutate(log2.odds.ratio = ifelse(log2.odds.ratio > 0.5, 0.5, log2.odds.ratio),
         log2.odds.ratio = ifelse(log2.odds.ratio < -0.5, -0.5, log2.odds.ratio))

p_odds_ratio <- plot_data %>%
  # filter(p.value < 1E-20) %>%
  # filter(SE < 0.15) %>%
  ggplot(aes(x = cluster_label_super, y = forcats::fct_rev(contrast), color = log2.odds.ratio, size = -log10(p.value))) +
  geom_point() +
  scale_color_gradientn(
    colors = rev(brewer.pal(9, "RdBu")),
    # values = rescale(c(min(plot_data$log2.odds.ratio, na.rm=T), -0.5, 0, 0.5, max(plot_data$log2.odds.ratio, na.rm=T))),
    limits = c(-0.5, 0.5),
    # limits = c(min(plot_data$log2.odds.ratio, na.rm=T), max(plot_data$log2.odds.ratio, na.rm=T)),
    labels = c("≤-0.5", 0, "≥+0.5"),
    breaks = c(-0.5, 0, 0.5)
  ) +
  # scale_color_gradientn(colours = viridis(9), labels = c("≤-1", 0, 2, "≥4"),
  #                       breaks = c(-1, 0, 2, 4), limits = c(-1, 4)) +
  scale_size_continuous(
    limits = c(0, 250),
    breaks = c(0, 125, 250),
    labels = c(0, 125, 250)
  ) +
  scale_x_discrete(drop = FALSE) +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.title = element_text(size=14),
        legend.direction = "horizontal", 
        legend.position = "top",
        legend.box = "horizontal") +
  guides(color = guide_colourbar(title.position="top", title.hjust = 0.5, title.vjust = 0),
         size = guide_legend(title.position="top", title.hjust = 0.5, title.vjust = 0)) +
  labs(title = NULL, x = NULL, y = NULL, color = 'log2(odds ratio)', size = "\n-log10(p value)") +
  facet_grid(contrast_variable ~ ., scales = "free_y", space = "free")

p_signature_site_anno <- plot_data %>% 
  distinct(contrast, contrast_variable, .keep_all = T) %>% 
  ggplot() +
  geom_tile(aes(x=0, y=forcats::fct_rev(contrast), fill = contrast)) +
  common_heat_layers + 
  scale_fill_manual(values = c(clrs$consensus_signature, clrs$tumor_supersite)) +
  facet_grid(contrast_variable~., scales = "free", space = "free") +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        strip.text = element_blank()) +
  guides(fill = F)

p_cluster_anno <- plot_data %>% 
  mutate(facet_helper = "") %>% 
  distinct(cluster_label_super, facet_helper, .keep_all = T) %>% 
  ggplot() +
  geom_tile(aes(cluster_label_super, facet_helper, fill = cluster_label_super)) +
  geom_point(aes(cluster_label_super, facet_helper), color = "white", alpha = 0.5, size = 5) +
  geom_text(aes(cluster_label_super, facet_helper, label = as.numeric(cluster_label_super))) +
  common_heat_layers +
  scale_fill_manual(values = clrs$cluster_label_super$Myeloid.super) +
  scale_x_discrete(drop = FALSE) +
  facet_grid(~facet_helper, scales = "free", space = "free") +
  theme(axis.text.y = element_blank(),
        strip.text = element_blank()) +
  guides(fill = F)

p_left <-
  plot_grid(
    p_signature_site_anno + theme(plot.margin = margin(t = 6, r = 0, b = 0, l = 6)),
    ggdraw(),
    nrow = 2,
    align = "hv",
    axis = "tbr",
    rel_heights = c(1, 0.35),
    rel_widths = c(0.75, 1)
  )

p_right <-
  plot_grid(
    p_odds_ratio + theme(legend.position = "none", plot.margin = margin(t = 6, r = 6, b = 0, l = 0)),
    p_cluster_anno + theme(plot.margin = margin(t = 0, r = 6, b = 6, l = 6)),
    nrow = 2,
    align = "v",
    axis = "lr",
    rel_heights = c(1, 0.35),
    rel_widths = c(0.75, 1)
  )

p <- plot_grid(
  plot_grid(
    p_left,
    p_right,
    nrow = 1,
    align = "hv",
    axis = "tblr",
    rel_widths = c(1, 1)
    ),
  get_legend(p_odds_ratio),
  ncol = 1,
  rel_heights = c(1, 0.2)
  )

p

ggsave_pdf("figures/630_Myeloid_cell_glm/630_Myeloid_cell_cluster_super_odds_ratio.pdf", p,
           width = 3.6, height = 5)
ggsave_png("figures/630_Myeloid_cell_glm/630_Myeloid_cell_cluster_super_odds_ratio.png", p,
           width = 3.6, height = 5)

```

## Myeloid cell clusters {.tabset}

```{r}

scrna_cluster_sample_tbl <- scrna_cell_tbl %>%
  # filter(tumor_supersite != "Ascites") %>%
  mutate(cell_type = as.character(cell_type)) %>%
  group_by(patient_id, consensus_signature, consensus_signature_short, tumor_type, tumor_supersite, tumor_subsite, therapy, sort_parameters, cell_type, cluster_label) %>%
  summarize(cell_state_count = n_distinct(cell_id)) %>% 
  mutate(
      other_cell_state_count = sum(cell_state_count) - cell_state_count,
      total_cell_state_count = sum(cell_state_count),
      cell_state_proportion = cell_state_count/total_cell_state_count*100
      ) %>%
  ungroup

```

```{r}

data[["Monocyte"]] <- scrna_cluster_sample_tbl %>%
  filter(str_detect(sort_parameters, "U|CD45+")) %>%
  filter(str_detect(cell_type, "Monocyte")) %>%
  filter(!is.na(cluster_label))
formulas[["Monocyte"]] <-cbind(cell_state_count, other_cell_state_count) ~ cluster_label * consensus_signature + cluster_label * tumor_supersite #+ cluster_label * sort_parameters
models[["Monocyte"]] <- glm(formula = formulas[["Monocyte"]], family = binomial(link = 'logit'), data = data[["Monocyte"]])

consensus_signature_emm[["Monocyte"]] <- emmeans(models[["Monocyte"]], specs = eff ~ consensus_signature | cluster_label, type = "response", tran = "logit", adjust = "bonferroni")
consensus_signature_odds <- consensus_signature_emm[["Monocyte"]]$contrasts %>%
  rbind() %>%
  as.data.frame()

site_emm[["Monocyte"]] <- emmeans(models[["Monocyte"]], specs = eff ~ tumor_supersite | cluster_label, type = "response", tran = "logit", adjust = "bonferroni")
site_odds <- site_emm[["Monocyte"]]$contrasts %>%
  rbind() %>%
  as.data.frame()

```

```{r, fig.width = 4.5, fig.height = 5, results = "asis"}

plot_data <- bind_rows(consensus_signature_odds %>% add_column(contrast_variable = "Signature"),
                       site_odds %>% add_column(contrast_variable = "Site")) %>%
  mutate(p.value = ifelse(p.value < 1E-250, 1E-250, p.value)) %>%
  filter(!str_detect(contrast, "HRD effect")) %>%
  mutate(contrast = str_remove(contrast, " effect")) %>%
  mutate(contrast = str_remove(contrast, "\\(")) %>%
  mutate(contrast = str_remove(contrast, "\\)")) %>%
  mutate(contrast = ordered(contrast, levels = c(names(clrs$consensus_signature), names(clrs$tumor_supersite)))) %>%
  mutate(cluster_label = ordered(cluster_label, levels = names(clrs$cluster_label$Myeloid.super))) %>%
  filter(!str_detect(contrast, "Undetermined")) %>%
  filter(!str_detect(contrast, "Other")) %>%
  mutate(log2.odds.ratio = log2(odds.ratio)) %>%
  mutate(log2.odds.ratio = ifelse(log2.odds.ratio > 1, 1, log2.odds.ratio),
         log2.odds.ratio = ifelse(log2.odds.ratio < -1, -1, log2.odds.ratio))

p_odds_ratio <- plot_data %>%
  filter(p.value < 1E-20) %>%
  filter(SE < 0.15) %>%
  ggplot(aes(x = cluster_label, y = forcats::fct_rev(contrast), color = log2.odds.ratio, size = -log10(p.value))) +
  geom_point() +
  scale_color_gradientn(
    colors = rev(brewer.pal(9, "RdBu")),
    # values = rescale(c(min(plot_data$log2.odds.ratio, na.rm=T), -0.5, 0, 0.5, max(plot_data$log2.odds.ratio, na.rm=T))),
    limits = c(-1, 1),
    # limits = c(min(plot_data$log2.odds.ratio, na.rm=T), max(plot_data$log2.odds.ratio, na.rm=T)),
    labels = c("≤-1", 0, "≥1"),
    breaks = c(-1, 0, 1)
  ) +
  # scale_color_gradientn(
  #   colors = rev(brewer.pal(9, "RdBu")),
  #   values = rescale(c(min(plot_data$log2.odds.ratio, na.rm=T), -1, 0, 1, max(plot_data$log2.odds.ratio, na.rm=T))),
  #   limits = c(min(plot_data$log2.odds.ratio, na.rm=T), max(plot_data$log2.odds.ratio, na.rm=T)),
  #   breaks = c(-2, 0, 2)
  # ) +
  scale_size_continuous(
    limits = c(0, 250),
    breaks = c(0, 125, 250),
    labels = c(0, 125, 250)
  ) +
  scale_x_discrete(drop = FALSE) +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.title = element_text(size=14),
        legend.direction = "horizontal", 
        legend.position = "top",
        legend.box = "horizontal") +
  guides(color = guide_colourbar(title.position="top", title.hjust = 0.5, title.vjust = 0),
         size = guide_legend(title.position="top", title.hjust = 0.5, title.vjust = 0)) +
  labs(title = NULL, x = NULL, y = NULL, color = 'log2(odds ratio)', size = "\n-log10(p value)") +
  facet_grid(contrast_variable ~ ., scales = "free_y", space = "free")

p_signature_site_anno <- plot_data %>% 
  distinct(contrast, contrast_variable, .keep_all = T) %>% 
  ggplot() +
  geom_tile(aes(x=0, y=forcats::fct_rev(contrast), fill = contrast)) +
  heatmap_layers + 
  scale_fill_manual(values = c(clrs$consensus_signature, clrs$tumor_supersite)) +
  facet_grid(contrast_variable~., scales = "free", space = "free") +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        strip.text = element_blank()) +
  guides(fill = F)

p_cluster_anno <- plot_data %>% 
  mutate(facet_helper = "") %>% 
  distinct(cluster_label, facet_helper, .keep_all = T) %>% 
  ggplot() +
  geom_tile(aes(cluster_label, facet_helper, fill = cluster_label)) +
  geom_point(aes(cluster_label, facet_helper), color = "white", alpha = 0.5, size = 5) +
  geom_text(aes(cluster_label, facet_helper, label = as.numeric(cluster_label))) +
  heatmap_layers + 
  scale_fill_manual(values = clrs$cluster_label$Myeloid.super) +
  scale_x_discrete(drop = FALSE) +
  facet_grid(~facet_helper, scales = "free", space = "free") +
  theme(axis.text.y = element_blank(),
        strip.text = element_blank()) +
  guides(fill = F)

p_left <-
  plot_grid(
    p_signature_site_anno + theme(plot.margin = margin(t = 6, r = 0, b = 0, l = 6)),
    ggdraw(),
    nrow = 2,
    align = "hv",
    axis = "tbr",
    rel_heights = c(1, 0.7),
    rel_widths = c(0.75, 1)
  )

p_right <-
  plot_grid(
    p_odds_ratio + theme(legend.position = "none", plot.margin = margin(t = 6, r = 6, b = 0, l = 0)),
    p_cluster_anno + theme(plot.margin = margin(t = 0, r = 6, b = 6, l = 6)),
    nrow = 2,
    align = "v",
    axis = "lr",
    rel_heights = c(1, 0.7),
    rel_widths = c(0.75, 1)
  )

p <- plot_grid(
  plot_grid(
    p_left,
    p_right,
    nrow = 1,
    align = "hv",
    axis = "tblr",
    rel_widths = c(0.66, 1)
    ),
  get_legend(p_odds_ratio),
  ncol = 1,
  rel_heights = c(1, 0.175)
  )

p

ggsave_pdf("figures/630_Myeloid_cell_glm/630_Myeloid_cell_cluster_odds_ratio.pdf", p,
           width = 4.25, height = 5)
ggsave_png("figures/630_Myeloid_cell_glm/630_Myeloid_cell_cluster_odds_ratio.png", p,
           width = 4.25, height = 5)

```
